package com.tpverp.backend.pdawork;
import com.tpverp.backend.catalog.*;import com.tpverp.backend.organization.CurrentOrganization;
import java.math.BigDecimal;import java.time.*;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service
public class PdaInventoryTraceService{
 private final PdaWarehouseLocationRepository locations;private final PdaStockLotRepository lots;private final WarehouseRepository warehouses;private final ProductRepository products;private final CurrentOrganization organization;private final Clock clock;
 public PdaInventoryTraceService(PdaWarehouseLocationRepository locations,PdaStockLotRepository lots,WarehouseRepository warehouses,ProductRepository products,CurrentOrganization organization,Clock clock){this.locations=locations;this.lots=lots;this.warehouses=warehouses;this.products=products;this.organization=organization;this.clock=clock;}
 @Transactional(readOnly=true)public List<LocationView> locations(UUID warehouseId){warehouse(warehouseId);return locations.findByStoreIdAndWarehouseIdAndActiveTrueOrderByCode(storeId(),warehouseId).stream().map(LocationView::from).toList();}
 @Transactional public LocationView createLocation(UUID warehouseId,String code,String description){warehouse(warehouseId);if(locations.findByStoreIdAndWarehouseIdAndCodeIgnoreCaseAndActiveTrue(storeId(),warehouseId,code).isPresent())throw new IllegalArgumentException("La ubicación ya existe");return LocationView.from(locations.save(new PdaWarehouseLocation(storeId(),warehouseId,code,description)));}
 @Transactional public LocationView deactivateLocation(UUID id,long version){var value=locations.findById(id).filter(v->v.getStoreId().equals(storeId())).orElseThrow(()->new IllegalArgumentException("Ubicación no encontrada"));value.deactivate(version);return LocationView.from(locations.save(value));}
 @Transactional public LotView receive(ReceiveLot command){warehouse(command.warehouseId());if(command.productId()!=null)products.findById(command.productId()).filter(p->p.getStoreId().equals(storeId())).orElseThrow(()->new IllegalArgumentException("Producto no encontrado"));var lot=new PdaStockLot(storeId(),command.warehouseId(),command.productId(),command.productCode(),command.lotNumber(),command.expiryDate(),command.supplierId(),command.supplierReference(),command.quantity(),Instant.now(clock));return LotView.from(lots.save(lot));}
 @Transactional(readOnly=true)public List<LotView> lots(UUID warehouseId,String productCode,LocalDate expiresBefore){warehouse(warehouseId);return lots.findByStoreIdAndWarehouseIdAndProductCodeIgnoreCaseAndQuantityGreaterThanOrderByExpiryDateAscReceivedAtAsc(storeId(),warehouseId,productCode,BigDecimal.ZERO).stream().filter(v->expiresBefore==null||v.getExpiryDate()!=null&&!v.getExpiryDate().isAfter(expiresBefore)).map(LotView::from).toList();}
 @Transactional(readOnly=true)public List<FefoAllocation> planFefo(UUID warehouseId,String productCode,BigDecimal requested){if(requested==null||requested.signum()<=0)throw new IllegalArgumentException("Cantidad debe ser positiva");var remaining=requested;var result=new ArrayList<FefoAllocation>();for(var lot:lots.findByStoreIdAndWarehouseIdAndProductCodeIgnoreCaseAndQuantityGreaterThanOrderByExpiryDateAscReceivedAtAsc(storeId(),warehouseId,productCode,BigDecimal.ZERO)){if(remaining.signum()==0)break;var amount=remaining.min(lot.getQuantity());result.add(new FefoAllocation(lot.getId(),lot.getLotNumber(),lot.getExpiryDate(),amount,lot.getVersion()));remaining=remaining.subtract(amount);}if(remaining.signum()>0)throw new IllegalArgumentException("Stock de lotes insuficiente");return result;}
 @Transactional public LotView consume(UUID id,BigDecimal quantity,long version){var lot=lots.findByIdAndStoreId(id,storeId()).orElseThrow(()->new IllegalArgumentException("Lote no encontrado"));lot.consume(quantity,version,Instant.now(clock));return LotView.from(lots.save(lot));}
 private UUID storeId(){return organization.currentStore().getId();}private void warehouse(UUID id){warehouses.findById(id).filter(v->v.getStoreId().equals(storeId())).orElseThrow(()->new IllegalArgumentException("Almacén no encontrado"));}
 public record ReceiveLot(UUID warehouseId,UUID productId,String productCode,String lotNumber,LocalDate expiryDate,UUID supplierId,String supplierReference,BigDecimal quantity){}
 public record LocationView(UUID id,UUID warehouseId,String code,String description,boolean active,long version){static LocationView from(PdaWarehouseLocation v){return new LocationView(v.getId(),v.getWarehouseId(),v.getCode(),v.getDescription(),v.isActive(),v.getVersion());}}
 public record LotView(UUID id,UUID warehouseId,UUID productId,String productCode,String lotNumber,LocalDate expiryDate,UUID supplierId,String supplierReference,BigDecimal quantity,Instant receivedAt,long version){static LotView from(PdaStockLot v){return new LotView(v.getId(),v.getWarehouseId(),v.getProductId(),v.getProductCode(),v.getLotNumber(),v.getExpiryDate(),v.getSupplierId(),v.getSupplierReference(),v.getQuantity(),v.getReceivedAt(),v.getVersion());}}
 public record FefoAllocation(UUID lotId,String lotNumber,LocalDate expiryDate,BigDecimal quantity,long version){}
}
