import type { LocaleCode } from "../types";

const es: Record<string, string> = {
  "common.refresh": "Actualizar", "common.saving": "Guardando...",
  "gestion.security.navigation": "Seguridad", "gestion.security.eyebrow": "Administración y acceso",
  "gestion.security.search": "Buscar", "gestion.security.results": "{count} registros", "gestion.security.resize": "Cambiar ancho de",
  "gestion.security.loadError": "No se pudieron cargar los datos de seguridad", "gestion.security.saveError": "No se pudieron guardar los cambios",
  "gestion.users.navigation": "Usuarios", "gestion.users.title": "Usuarios", "gestion.users.subtitle": "Cuentas autorizadas para trabajar en esta tienda",
  "gestion.users.new": "Nuevo usuario", "gestion.users.searchPlaceholder": "Código, nombre, acceso o rol", "gestion.users.empty": "No hay usuarios para mostrar", "gestion.users.select": "Selecciona un usuario",
  "gestion.users.column.userId": "Código", "gestion.users.column.name": "Nombre", "gestion.users.column.userName": "Identificador de acceso", "gestion.users.column.role": "Rol", "gestion.users.column.status": "Estado",
  "gestion.users.active": "Activo", "gestion.users.inactive": "Desactivado", "gestion.users.protected": "Cuenta protegida", "gestion.users.adminProtected": "La cuenta ADMIN se gestiona mediante las operaciones protegidas del administrador.",
  "gestion.users.editIdentity": "Editar identidad", "gestion.users.changeRole": "Cambiar rol", "gestion.users.resetPassword": "Restablecer PIN", "gestion.users.discountPolicy": "Limite de descuento", "gestion.users.activate": "Activar", "gestion.users.deactivate": "Desactivar",
  "gestion.users.dialog.create": "Crear usuario", "gestion.users.dialog.identity": "Editar identidad", "gestion.users.dialog.role": "Cambiar rol", "gestion.users.dialog.password": "Restablecer PIN",
  "gestion.users.field.name": "Nombre", "gestion.users.field.userName": "Identificador de acceso", "gestion.users.field.role": "Rol", "gestion.users.field.password": "Nuevo PIN", "gestion.users.field.confirmPassword": "Confirmar PIN", "gestion.users.field.maxDiscount": "Descuento maximo (%)", "gestion.users.dialog.discount": "Configurar limite de descuento", "gestion.users.discountInvalid": "El limite debe estar entre 0 y 100.",
  "gestion.users.passwordInvalid": "El PIN debe contener entre 4 y 12 cifras y coincidir en ambos campos.",
  "gestion.users.confirmActivateTitle": "Activar usuario", "gestion.users.confirmDeactivateTitle": "Desactivar usuario", "gestion.users.confirmActivate": "¿Activar a {name}?", "gestion.users.confirmDeactivate": "¿Desactivar a {name} y revocar sus sesiones abiertas?",
  "gestion.roles.navigation": "Roles y permisos", "gestion.roles.title": "Roles y permisos", "gestion.roles.subtitle": "Define las capacidades de cada perfil de trabajo",
  "gestion.roles.new": "Nuevo rol", "gestion.roles.empty": "No hay roles para mostrar", "gestion.roles.select": "Selecciona un rol", "gestion.roles.system": "Rol del sistema", "gestion.roles.custom": "Rol configurable", "gestion.roles.detail": "Configuración del rol",
  "gestion.roles.selectedCount": "{count} permisos seleccionados", "gestion.roles.toggleGroup": "Marcar grupo", "gestion.roles.savePermissions": "Guardar permisos", "gestion.roles.adminProtected": "Acceso total permanente", "gestion.roles.adminProtectedHint": "El rol ADMIN está protegido y no admite cambios en sus permisos.",
  "gestion.roles.dialog.create": "Crear rol", "gestion.roles.dialog.rename": "Renombrar rol", "gestion.roles.dialog.delete": "Eliminar rol", "gestion.roles.field.name": "Nombre del rol",
  "gestion.roles.rename": "Renombrar", "gestion.roles.delete": "Eliminar", "gestion.roles.deleteConfirm": "¿Eliminar el rol {name}?", "gestion.roles.deleteRequirement": "Solo puede eliminarse si no tiene usuarios asignados.",
  "gestion.permissions.group.SECURITY": "Seguridad", "gestion.permissions.group.TERMINAL": "Terminales", "gestion.permissions.group.SYSTEM": "Sistema", "gestion.permissions.group.CONTROL": "Control", "gestion.permissions.group.CATALOG": "Productos", "gestion.permissions.group.INVENTORY": "Stock y almacenes", "gestion.permissions.group.PARTY": "Clientes y proveedores", "gestion.permissions.group.DOCUMENTS": "Ventas y documentos", "gestion.permissions.group.CASH": "Caja y cuentas", "gestion.permissions.group.FISCAL": "VERI*FACTU",
  "security.permissions.appGestionAccess": "Acceso a APP GESTIÓN", "security.permissions.users": "Administración heredada de usuarios", "security.permissions.userManagement": "Gestión de usuarios", "security.permissions.roles": "Gestión de roles y permisos", "security.permissions.terminals": "Administración de terminales", "security.permissions.licenses": "Gestión de licencias", "security.permissions.backups": "Gestión de copias de seguridad", "security.permissions.audit": "Consulta de auditoría",
  "terminal.permissions.configure": "Configuración de terminal", "terminal.permissions.payment.void": "Anular operación de datáfono", "terminal.permissions.payment.refund": "Reembolsar operación de datáfono", "terminal.permissions.payment.secrets": "Gestionar secretos de datáfono",
  "control.permissions.alerts.read": "Consultar alertas de control", "control.permissions.alerts.manage": "Gestionar alertas de control", "control.permissions.rules.manage": "Gestionar reglas de control",
  "verifactu.permissions.read": "Consultar VERI*FACTU", "verifactu.permissions.correct": "Crear subsanaciones VERI*FACTU", "verifactu.permissions.manage": "Gestionar reintentos y diagnósticos VERI*FACTU",
  "catalog.permissions.read": "Consultar productos", "catalog.permissions.write": "Crear y modificar productos", "catalog.permissions.delete": "Eliminar productos", "catalog.permissions.productManagement": "Gestión completa de productos", "catalog.permissions.taxes": "Gestionar impuestos",
  "inventory.permissions.warehouseManagement": "Gestión de almacén", "inventory.permissions.warehouses": "Gestionar almacenes", "inventory.permissions.read": "Consultar stock", "inventory.permissions.adjust": "Realizar ajustes de stock", "inventory.permissions.transfer": "Transferir stock",
  "party.permissions.customers.read": "Consultar clientes", "party.permissions.customers.write": "Crear y modificar clientes", "party.permissions.customers.delete": "Eliminar clientes", "party.permissions.suppliers.read": "Consultar proveedores", "party.permissions.suppliers.write": "Crear y modificar proveedores", "party.permissions.suppliers.delete": "Eliminar proveedores", "party.permissions.management": "Gestión de clientes y proveedores",
  "document.permissions.sales.operate": "Realizar ventas", "document.permissions.sales.manage": "Gestión de ventas e informes", "document.permissions.sales.changePrice": "Cambiar precios en venta", "document.permissions.sales.applyDiscount": "Aplicar descuentos manuales", "document.permissions.deliveryNotes.read": "Consultar albaranes", "document.permissions.deliveryNotes.write": "Crear y modificar albaranes", "document.permissions.deliveryNotes.confirm": "Confirmar albaranes", "document.permissions.tickets.read": "Consultar tickets", "document.permissions.tickets.create": "Crear tickets", "document.permissions.tickets.cancel": "Anular tickets", "document.permissions.invoices.read": "Consultar facturas", "document.permissions.invoices.write": "Crear y modificar facturas", "document.permissions.invoices.confirm": "Confirmar facturas", "document.permissions.invoices.pay": "Registrar pagos de facturas",
  "cash.permissions.accounting": "Gestión de caja y contabilidad", "cash.permissions.read": "Consultar caja", "cash.permissions.operate": "Operar caja", "cash.permissions.configure": "Configurar caja"
};

const en: Record<string, string> = {
  ...es,
  "common.refresh": "Refresh", "common.saving": "Saving...", "gestion.security.navigation": "Security", "gestion.security.eyebrow": "Administration and access",
  "gestion.security.search": "Search", "gestion.security.results": "{count} records", "gestion.security.resize": "Resize", "gestion.security.loadError": "Security data could not be loaded", "gestion.security.saveError": "Changes could not be saved",
  "gestion.users.navigation": "Users", "gestion.users.title": "Users", "gestion.users.subtitle": "Accounts authorized to work in this store", "gestion.users.new": "New user", "gestion.users.searchPlaceholder": "Code, name, login or role", "gestion.users.empty": "No users to display", "gestion.users.select": "Select a user",
  "gestion.users.column.userId": "Code", "gestion.users.column.name": "Name", "gestion.users.column.userName": "Login name", "gestion.users.column.role": "Role", "gestion.users.column.status": "Status", "gestion.users.active": "Active", "gestion.users.inactive": "Disabled", "gestion.users.protected": "Protected account", "gestion.users.adminProtected": "The ADMIN account is managed through protected administrator operations.",
  "gestion.users.editIdentity": "Edit identity", "gestion.users.changeRole": "Change role", "gestion.users.resetPassword": "Reset PIN", "gestion.users.discountPolicy": "Discount limit", "gestion.users.activate": "Activate", "gestion.users.deactivate": "Deactivate", "gestion.users.dialog.create": "Create user", "gestion.users.dialog.identity": "Edit identity", "gestion.users.dialog.role": "Change role", "gestion.users.dialog.password": "Reset PIN", "gestion.users.dialog.discount": "Configure discount limit",
  "gestion.users.field.name": "Name", "gestion.users.field.userName": "Login name", "gestion.users.field.role": "Role", "gestion.users.field.password": "New PIN", "gestion.users.field.confirmPassword": "Confirm PIN", "gestion.users.field.maxDiscount": "Maximum discount (%)", "gestion.users.discountInvalid": "The limit must be between 0 and 100.", "gestion.users.passwordInvalid": "The PIN must contain 4 to 12 digits and match in both fields.",
  "gestion.users.confirmActivateTitle": "Activate user", "gestion.users.confirmDeactivateTitle": "Deactivate user", "gestion.users.confirmActivate": "Activate {name}?", "gestion.users.confirmDeactivate": "Deactivate {name} and revoke open sessions?",
  "gestion.roles.navigation": "Roles and permissions", "gestion.roles.title": "Roles and permissions", "gestion.roles.subtitle": "Define the capabilities of each work profile", "gestion.roles.new": "New role", "gestion.roles.empty": "No roles to display", "gestion.roles.select": "Select a role", "gestion.roles.system": "System role", "gestion.roles.custom": "Configurable role", "gestion.roles.detail": "Role configuration", "gestion.roles.selectedCount": "{count} permissions selected", "gestion.roles.toggleGroup": "Toggle group", "gestion.roles.savePermissions": "Save permissions", "gestion.roles.adminProtected": "Permanent full access", "gestion.roles.adminProtectedHint": "The ADMIN role is protected and its permissions cannot be changed.", "gestion.roles.dialog.create": "Create role", "gestion.roles.dialog.rename": "Rename role", "gestion.roles.dialog.delete": "Delete role", "gestion.roles.field.name": "Role name",
  "gestion.roles.rename": "Rename", "gestion.roles.delete": "Delete", "gestion.roles.deleteConfirm": "Delete the {name} role?", "gestion.roles.deleteRequirement": "It can only be deleted when no users are assigned to it.",
  "gestion.permissions.group.SECURITY": "Security", "gestion.permissions.group.TERMINAL": "Terminals", "gestion.permissions.group.SYSTEM": "System", "gestion.permissions.group.CONTROL": "Control", "gestion.permissions.group.CATALOG": "Products", "gestion.permissions.group.INVENTORY": "Stock and warehouses", "gestion.permissions.group.PARTY": "Customers and suppliers", "gestion.permissions.group.DOCUMENTS": "Sales and documents", "gestion.permissions.group.CASH": "Cash and accounts", "gestion.permissions.group.FISCAL": "VERI*FACTU",
  "security.permissions.appGestionAccess": "Access APP GESTION", "security.permissions.users": "Legacy user administration", "security.permissions.userManagement": "User management", "security.permissions.roles": "Role and permission management", "security.permissions.terminals": "Terminal administration", "security.permissions.licenses": "License management", "security.permissions.backups": "Backup management", "security.permissions.audit": "Audit access",
  "terminal.permissions.configure": "Terminal configuration", "terminal.permissions.payment.void": "Void payment terminal operation", "terminal.permissions.payment.refund": "Refund payment terminal operation", "terminal.permissions.payment.secrets": "Manage payment terminal secrets",
  "control.permissions.alerts.read": "View control alerts", "control.permissions.alerts.manage": "Manage control alerts", "control.permissions.rules.manage": "Manage control rules",
  "verifactu.permissions.read": "View VERI*FACTU", "verifactu.permissions.correct": "Create VERI*FACTU corrections", "verifactu.permissions.manage": "Manage VERI*FACTU retries and diagnostics",
  "catalog.permissions.read": "View products", "catalog.permissions.write": "Create and update products", "catalog.permissions.delete": "Delete products", "catalog.permissions.productManagement": "Full product management", "catalog.permissions.taxes": "Manage taxes",
  "inventory.permissions.warehouseManagement": "Warehouse management", "inventory.permissions.warehouses": "Manage warehouses", "inventory.permissions.read": "View stock", "inventory.permissions.adjust": "Adjust stock", "inventory.permissions.transfer": "Transfer stock",
  "party.permissions.customers.read": "View customers", "party.permissions.customers.write": "Create and update customers", "party.permissions.customers.delete": "Delete customers", "party.permissions.suppliers.read": "View suppliers", "party.permissions.suppliers.write": "Create and update suppliers", "party.permissions.suppliers.delete": "Delete suppliers", "party.permissions.management": "Customer and supplier management",
  "document.permissions.sales.operate": "Process sales", "document.permissions.sales.manage": "Sales and report management", "document.permissions.sales.changePrice": "Change sale prices", "document.permissions.sales.applyDiscount": "Apply manual discounts", "document.permissions.deliveryNotes.read": "View delivery notes", "document.permissions.deliveryNotes.write": "Create and update delivery notes", "document.permissions.deliveryNotes.confirm": "Confirm delivery notes", "document.permissions.tickets.read": "View tickets", "document.permissions.tickets.create": "Create tickets", "document.permissions.tickets.cancel": "Cancel tickets", "document.permissions.invoices.read": "View invoices", "document.permissions.invoices.write": "Create and update invoices", "document.permissions.invoices.confirm": "Confirm invoices", "document.permissions.invoices.pay": "Record invoice payments",
  "cash.permissions.accounting": "Cash and accounting management", "cash.permissions.read": "View cash", "cash.permissions.operate": "Operate cash", "cash.permissions.configure": "Configure cash"
};

const zh: Record<string, string> = {
  ...en,
  "common.refresh": "刷新", "common.saving": "正在保存...",
  "gestion.security.navigation": "安全管理", "gestion.security.eyebrow": "管理与访问权限", "gestion.security.search": "搜索", "gestion.security.results": "{count} 条记录", "gestion.security.resize": "调整列宽",
  "gestion.security.loadError": "无法加载安全管理数据", "gestion.security.saveError": "无法保存更改",
  "gestion.users.navigation": "用户", "gestion.users.title": "用户", "gestion.users.subtitle": "获准在本门店工作的账户", "gestion.users.new": "新建用户", "gestion.users.searchPlaceholder": "编号、姓名、登录名或角色", "gestion.users.empty": "没有可显示的用户", "gestion.users.select": "请选择用户",
  "gestion.users.column.userId": "编号", "gestion.users.column.name": "姓名", "gestion.users.column.userName": "登录名", "gestion.users.column.role": "角色", "gestion.users.column.status": "状态",
  "gestion.users.active": "启用", "gestion.users.inactive": "已停用", "gestion.users.protected": "受保护账户", "gestion.users.adminProtected": "ADMIN 账户只能通过受保护的管理员操作进行管理。",
  "gestion.users.editIdentity": "编辑身份信息", "gestion.users.changeRole": "更改角色", "gestion.users.resetPassword": "重置 PIN", "gestion.users.discountPolicy": "折扣上限", "gestion.users.activate": "启用", "gestion.users.deactivate": "停用",
  "gestion.users.dialog.create": "创建用户", "gestion.users.dialog.identity": "编辑身份信息", "gestion.users.dialog.role": "更改角色", "gestion.users.dialog.password": "重置 PIN",
  "gestion.users.field.name": "姓名", "gestion.users.field.userName": "登录名", "gestion.users.field.role": "角色", "gestion.users.field.password": "新 PIN", "gestion.users.field.confirmPassword": "确认 PIN", "gestion.users.field.maxDiscount": "最大折扣 (%)", "gestion.users.dialog.discount": "设置折扣上限", "gestion.users.discountInvalid": "折扣上限必须在 0 到 100 之间。",
  "gestion.users.passwordInvalid": "PIN 必须由 4 至 12 位数字组成，且两次输入必须一致。", "gestion.users.confirmActivateTitle": "启用用户", "gestion.users.confirmDeactivateTitle": "停用用户", "gestion.users.confirmActivate": "要启用 {name} 吗？", "gestion.users.confirmDeactivate": "要停用 {name} 并撤销其当前会话吗？",
  "gestion.roles.navigation": "角色与权限", "gestion.roles.title": "角色与权限", "gestion.roles.subtitle": "定义每个工作角色可执行的操作", "gestion.roles.new": "新建角色", "gestion.roles.empty": "没有可显示的角色", "gestion.roles.select": "请选择角色", "gestion.roles.system": "系统角色", "gestion.roles.custom": "可配置角色", "gestion.roles.detail": "角色配置",
  "gestion.roles.selectedCount": "已选择 {count} 项权限", "gestion.roles.toggleGroup": "切换整组", "gestion.roles.savePermissions": "保存权限", "gestion.roles.adminProtected": "永久拥有全部访问权限", "gestion.roles.adminProtectedHint": "ADMIN 角色受系统保护，不能修改其权限。", "gestion.roles.dialog.create": "创建角色", "gestion.roles.dialog.rename": "重命名角色", "gestion.roles.dialog.delete": "删除角色", "gestion.roles.field.name": "角色名称",
  "gestion.roles.rename": "重命名", "gestion.roles.delete": "删除", "gestion.roles.deleteConfirm": "要删除角色 {name} 吗？", "gestion.roles.deleteRequirement": "仅当该角色未分配给任何用户时才能删除。",
  "gestion.permissions.group.SECURITY": "安全", "gestion.permissions.group.TERMINAL": "终端", "gestion.permissions.group.SYSTEM": "系统", "gestion.permissions.group.CONTROL": "控制", "gestion.permissions.group.CATALOG": "商品", "gestion.permissions.group.INVENTORY": "库存与仓库", "gestion.permissions.group.PARTY": "客户与供应商", "gestion.permissions.group.DOCUMENTS": "销售与单据", "gestion.permissions.group.CASH": "收银与账户", "gestion.permissions.group.FISCAL": "VERI*FACTU",
  "security.permissions.appGestionAccess": "访问 APP GESTIÓN", "security.permissions.users": "旧版用户管理", "security.permissions.userManagement": "用户管理", "security.permissions.roles": "角色与权限管理", "security.permissions.terminals": "终端管理", "security.permissions.licenses": "许可证管理", "security.permissions.backups": "备份管理", "security.permissions.audit": "查看审计记录",
  "terminal.permissions.configure": "终端配置", "terminal.permissions.payment.void": "撤销支付终端交易", "terminal.permissions.payment.refund": "退还支付终端交易", "terminal.permissions.payment.secrets": "管理支付终端密钥",
  "control.permissions.alerts.read": "查看控制警报", "control.permissions.alerts.manage": "管理控制警报", "control.permissions.rules.manage": "管理控制规则",
  "verifactu.permissions.read": "查看 VERI*FACTU", "verifactu.permissions.correct": "创建 VERI*FACTU 更正", "verifactu.permissions.manage": "管理 VERI*FACTU 重试和诊断",
  "catalog.permissions.read": "查看商品", "catalog.permissions.write": "创建和修改商品", "catalog.permissions.delete": "删除商品", "catalog.permissions.productManagement": "完整商品管理", "catalog.permissions.taxes": "管理税务设置",
  "inventory.permissions.warehouseManagement": "仓库管理", "inventory.permissions.warehouses": "管理仓库", "inventory.permissions.read": "查看库存", "inventory.permissions.adjust": "调整库存", "inventory.permissions.transfer": "调拨库存",
  "party.permissions.customers.read": "查看客户", "party.permissions.customers.write": "创建和修改客户", "party.permissions.customers.delete": "删除客户", "party.permissions.suppliers.read": "查看供应商", "party.permissions.suppliers.write": "创建和修改供应商", "party.permissions.suppliers.delete": "删除供应商", "party.permissions.management": "客户与供应商管理",
  "document.permissions.sales.operate": "执行销售", "document.permissions.sales.manage": "销售与报表管理", "document.permissions.sales.changePrice": "更改销售价格", "document.permissions.sales.applyDiscount": "应用手工折扣", "document.permissions.deliveryNotes.read": "查看送货单", "document.permissions.deliveryNotes.write": "创建和修改送货单", "document.permissions.deliveryNotes.confirm": "确认送货单", "document.permissions.tickets.read": "查看小票", "document.permissions.tickets.create": "创建小票", "document.permissions.tickets.cancel": "作废小票", "document.permissions.invoices.read": "查看发票", "document.permissions.invoices.write": "创建和修改发票", "document.permissions.invoices.confirm": "确认发票", "document.permissions.invoices.pay": "登记发票付款",
  "cash.permissions.accounting": "收银与会计管理", "cash.permissions.read": "查看收银数据", "cash.permissions.operate": "执行收银操作", "cash.permissions.configure": "配置收银"
};

export function securityMessages(locale: LocaleCode): Record<string, string> {
  return locale === "es" ? es : locale === "zh" ? zh : en;
}
