import { useEffect, useState } from "react";
import { apiRequest, ApiError } from "../api/client";
import { PaymentAllocationPanel } from "./PaymentAllocationPanel";
import type { PaymentSession } from "../sale/paymentOrchestration";
import { PaymentOperationPanel, type PaymentOperationEvent, type PaymentOperationView } from "./PaymentOperationPanel";
import { getHardwareBridge } from "../hardware/hardware";
import { loadPaymentOperationHistory, printPaymentReceipt, queryPaymentOperation, refundPaymentOperation, voidPaymentOperation } from "../sale/paymentOperations";
import type { Permission, TerminalContext } from "../types";

type Sale = { customerId: string | null; lines: Array<{ productId: string; quantity: number; discount: number }> };
type ServerSession = { id: string; total: number | string; status: string; ticketId?: string; ticketNumber?: string; allocations: Array<{ id: string; idempotencyKey: string; kind: "CASH"|"MANUAL_CARD"|"INTEGRATED_CARD"; amount: number|string; provider?: string; operationId?: string; status: string; reference?: string; authorization?: string; message?: string }> };
type Props = { totalCents: number; sale: Sale; token?: string; permissions: Permission[]; terminal: TerminalContext; disabled?: boolean; onFinalized: (ticketNumber: string) => void };
const uuid=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random()}`;
const map=(s:ServerSession):PaymentSession=>({id:s.id,totalCents:Math.round(Number(s.total)*100),status:s.status==="COVERED"||s.status==="FINALIZED"?"COVERED":"COLLECTING",allocations:s.allocations.map(a=>({...a,amountCents:Math.round(Number(a.amount)*100),status:a.status as never}))});

export function SalePaymentCheckout({totalCents,sale,token,permissions,terminal,disabled,onFinalized}:Props){
 const [server,setServer]=useState<ServerSession|null>(null);const [providers,setProviders]=useState<string[]>([]);const [capabilities,setCapabilities]=useState<string[]>([]);const [manual,setManual]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [operation,setOperation]=useState<PaymentOperationView|null>(null);const [events,setEvents]=useState<PaymentOperationEvent[]>([]);
 const storageKey=`tpverp.payment-session.${terminal.terminalId??terminal.terminalCode}`;
 useEffect(()=>{void apiRequest<{rules:{cardManualEnabled:boolean;integratedCardEnabled:boolean};providerDescriptors:Array<{provider:string;capabilities:string[]}>;configuration:{provider:string;enabled:boolean}}>("/terminal-configuration/payment",{token}).then(c=>{setManual(c.rules.cardManualEnabled);setProviders(c.rules.integratedCardEnabled&&c.configuration.enabled?[c.configuration.provider]:[]);setCapabilities(c.providerDescriptors.find(p=>p.provider===c.configuration.provider)?.capabilities??[]);}).catch(()=>{});},[token]);
 useEffect(()=>{const id=globalThis.sessionStorage?.getItem(storageKey);if(id)void apiRequest<ServerSession>(`/pos/payment-sessions/${id}`,{token}).then(s=>{if(s.status!=="FINALIZED"&&s.status!=="CANCELLED")setServer(s);else globalThis.sessionStorage?.removeItem(storageKey);}).catch(()=>globalThis.sessionStorage?.removeItem(storageKey));},[storageKey,token]);
 async function ensure(){if(server)return server;const id=uuid();const created=await apiRequest<ServerSession>("/pos/payment-sessions",{token,body:{sessionId:id,sale}});globalThis.sessionStorage?.setItem(storageKey,created.id);setServer(created);return created;}
 async function add(input:{kind:string;amountCents:number;provider?:string;reference?:string}){setBusy(true);setError("");try{const s=await ensure();const allocationId=uuid();const next=await apiRequest<ServerSession>(`/pos/payment-sessions/${s.id}/allocations`,{token,body:{allocationId,idempotencyKey:allocationId,kind:input.kind,amount:(input.amountCents/100).toFixed(2),provider:input.provider,reference:input.reference}});setServer(next);if(next.status==="COVERED"){const done=await apiRequest<ServerSession>(`/pos/payment-sessions/${next.id}/finalize`,{token,method:"POST"});setServer(done);if(done.ticketNumber){globalThis.sessionStorage?.removeItem(storageKey);onFinalized(done.ticketNumber);}}}catch(e){setError(e instanceof ApiError?e.message:"Resultado incierto; consulta el estado antes de continuar");}finally{setBusy(false);}}
 async function query(allocationId:string){if(!server)return;setBusy(true);try{const next=await apiRequest<ServerSession>(`/pos/payment-sessions/${server.id}/allocations/${allocationId}/query`,{token,method:"POST"});setServer(next);if(next.status==="COVERED"){const done=await apiRequest<ServerSession>(`/pos/payment-sessions/${next.id}/finalize`,{token,method:"POST"});setServer(done);if(done.ticketNumber)onFinalized(done.ticketNumber);}}catch(e){setError(e instanceof Error?e.message:"No se pudo consultar");}finally{setBusy(false);}}
 async function manage(id:string){setBusy(true);try{const [op,history]=await Promise.all([apiRequest<PaymentOperationView>(`/payment-terminal/operations/${id}`,{token}),loadPaymentOperationHistory(id,token)]);setOperation(op);setEvents(history);}finally{setBusy(false);}}
 if(!server)return <button type="button" disabled={disabled||busy||totalCents<=0} onClick={()=>void ensure().catch(e=>setError(e instanceof Error?e.message:"No se pudo iniciar el cobro"))}>Iniciar cobro dividido</button>;
 return <div aria-busy={busy}><PaymentAllocationPanel session={map(server)} providers={providers} manualCardEnabled={manual} onAdd={input=>void add(input)} onQuery={id=>void query(id)} onManage={id=>void manage(id)}/>{operation&&<PaymentOperationPanel operation={operation} events={events} capabilities={capabilities} permissions={permissions} onQuery={()=>void queryPaymentOperation(operation.id,token).then(setOperation)} onVoid={()=>{const password=globalThis.prompt?.("Contraseña de autorización")??"";void voidPaymentOperation(operation.id,token,password,uuid()).then(setOperation);}} onRefund={()=>{const amount=globalThis.prompt?.("Importe a reembolsar")??"";const password=globalThis.prompt?.("Contraseña de autorización")??"";void refundPaymentOperation(operation.id,token,amount,password,uuid()).then(setOperation);}} onPrintReceipt={()=>void printPaymentReceipt(operation.id,token,terminal,getHardwareBridge())}/>} {error&&<p role="alert">{error}</p>}</div>;
}
