import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from "react";
import { apiRequest, ApiError } from "../api/client";
import { createTranslator } from "../i18n/LocalizedMessages";
import { PaymentAllocationPanel } from "./PaymentAllocationPanel";
import type { PaymentSession } from "../sale/paymentOrchestration";
import { PaymentOperationPanel, type PaymentOperationEvent, type PaymentOperationView } from "./PaymentOperationPanel";
import { CashPaymentDialog } from "./CashPaymentDialog";
import { IndividualPaymentActions } from "./IndividualPaymentActions";
import { ManualCardReferenceDialog } from "./ManualCardReferenceDialog";
import { getHardwareBridge } from "../hardware/hardware";
import { loadPaymentOperationHistory, printPaymentReceipt, queryPaymentOperation, refundPaymentOperation, voidPaymentOperation } from "../sale/paymentOperations";
import type { LocaleCode, Permission, TerminalContext } from "../types";

type Sale = { customerId: string | null; lines: Array<{ productId: string; quantity: number; discount: number }> };
export type ServerSession = { id: string; total: number | string; status: string; ticketId?: string; ticketNumber?: string; allocations: Array<{ id: string; idempotencyKey: string; kind: "CASH"|"MANUAL_CARD"|"INTEGRATED_CARD"; amount: number|string; provider?: string; operationId?: string; status: string; reference?: string; authorization?: string; message?: string }> };
type Props = { locale: LocaleCode; totalCents: number; sale: Sale; token?: string; permissions: Permission[]; terminal: TerminalContext; disabled?: boolean; testCashEnabled?: boolean; onLockedChange?: (locked:boolean,reservedTotalCents?:number)=>void; onFinalized: (ticketNumber: string,totalCents:number,cashReceivedCents?:number) => void };
type AuthorizationAction = { kind: "VOID" | "REFUND"; amount: string };
type CashAttemptMetadata = { sessionId?: string; receivedCents: number };

const uuid=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random()}`;
const entryCleanupAttempted=new Set<string>();
const map=(s:ServerSession):PaymentSession=>({id:s.id,totalCents:Math.round(Number(s.total)*100),status:s.status==="COVERED"||s.status==="FINALIZED"?"COVERED":s.status==="COMPENSATION_REQUIRED"?"COMPENSATION_REQUIRED":"COLLECTING",allocations:s.allocations.map(a=>({...a,amountCents:Math.round(Number(a.amount)*100),status:a.status as never}))});
export const compensationGuidanceKey="payment.split.compensationGuidance";
export type PaymentLogoutPreparation="READY"|"BLOCKED";
export type SalePaymentCheckoutHandle={prepareLogout():Promise<PaymentLogoutPreparation>;prepareApplicationClose():Promise<PaymentLogoutPreparation>};
type CancellationResult="CANCELLED"|"NOT_CANCELLED"|"ERROR";
export async function prepareAutomaticExit(cancel:()=>Promise<CancellationResult>,_discard:()=>Promise<boolean>){return await cancel()==="CANCELLED"?"READY" as const:"BLOCKED" as const;}
export function paymentLogoutDisposition(session:ServerSession|null|undefined,hydrationComplete:boolean){
 if(!hydrationComplete)return "BLOCKED" as const;
 if(!session||session.status==="FINALIZED"||session.status==="CANCELLED")return "READY" as const;
 if(session.status!=="COLLECTING")return "BLOCKED" as const;
 return session.allocations.every(({status})=>["DECLINED","ERROR","CANCELLED"].includes(status))?"AUTO_CANCEL" as const:"BLOCKED" as const;
}
export function checkoutPresentation(status?:string|null,allocationStatuses:readonly string[]=[],safeRetry=false){
 if(!status||status==="FINALIZED"||status==="CANCELLED")return "INDIVIDUAL_ACTIONS";
 if(status==="COVERED")return "FINALIZE_RETRY";
 if(status==="COMPENSATION_REQUIRED")return "COMPENSATION";
 if(status==="COLLECTING"&&(safeRetry||(allocationStatuses.length>0&&allocationStatuses.every(value=>value==="DECLINED"||value==="ERROR"||value==="CANCELLED"))))return "INDIVIDUAL_ACTIONS";
 return "RECOVERY";
}
export function paymentSessionLocksSale(status:string|null|undefined){return !!status&&status!=="FINALIZED"&&status!=="CANCELLED";}
export function canManuallyFinalizePayment(status:string|null|undefined,busy:boolean){return status==="COVERED"&&!busy;}
export function paymentSessionAfterFinalization<T>(ticketNumber:string|undefined,session:T){return ticketNumber?null:session;}
export function stableAllocationAttempt<T>(stored:{sessionId:string;allocationId:string;input:T}|null,sessionId:string,input:T,generate:()=>string){return stored?.sessionId===sessionId&&JSON.stringify(stored.input)===JSON.stringify(input)?stored:{sessionId,allocationId:generate(),input};}
export function allocationFailureIsSafePreEffect(error:ApiError){return [400,401,403,404,409,422].includes(error.status);}
export function isMissingCashSessionError(message:string){return message.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("es").includes("sesion de caja abierta");}
export function shouldOfferTestCashSession(enabled:boolean,status:string|undefined,missing:boolean,terminalId?:string){return enabled&&status==="COVERED"&&missing&&Boolean(terminalId);}
export async function authorizationPasswordIsEphemeral<T>(password:string,clear:(value:string)=>void,operation:(password:string)=>Promise<T>){clear("");try{return await operation(password);}finally{clear("");}}
export async function compensationNoteIsEphemeral<T>(note:string,clear:(value:string)=>void,operation:(note:string)=>Promise<T>){const normalized=note.trim();clear("");try{return await operation(normalized);}finally{clear("");}}

export const SalePaymentCheckout=forwardRef<SalePaymentCheckoutHandle,Props>(function SalePaymentCheckout({locale,totalCents,sale,token,permissions,terminal,disabled,testCashEnabled=false,onLockedChange,onFinalized},ref){
 const t=createTranslator(locale);
 const [server,setServer]=useState<ServerSession|null>(null);const [providers,setProviders]=useState<string[]>([]);const [capabilities,setCapabilities]=useState<string[]>([]);const [manual,setManual]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [operation,setOperation]=useState<PaymentOperationView|null>(null);const [events,setEvents]=useState<PaymentOperationEvent[]>([]);
 const [authorization,setAuthorization]=useState<AuthorizationAction|null>(null);const [authorizationPassword,setAuthorizationPassword]=useState("");
 const [compensationDialog,setCompensationDialog]=useState(false);const [compensationNote,setCompensationNote]=useState("");
 const [cashOpen,setCashOpen]=useState(false);const cashGuardRef=useRef(false);const cashAttemptRef=useRef<CashAttemptMetadata|null>(null);
 const [manualCardOpen,setManualCardOpen]=useState(false);const cardGuardRef=useRef(false);
 const [safeRetry,setSafeRetry]=useState(false);
 const [testCashRequired,setTestCashRequired]=useState(false);
 const [testCashStatus,setTestCashStatus]=useState("");
 const [hydrationComplete,setHydrationComplete]=useState(false);
 const entryHydratedSessionIdRef=useRef<string|null>(null);
 const exitFeedbackRef=useRef<"payment.pending.logoutError"|"payment.pending.shutdownBlocked"|null>(null);
 const cleanupFlightRef=useRef<{sessionId:string;promise:Promise<boolean>}|null>(null);
 const storageKey=`tpverp.payment-session.${terminal.terminalId??terminal.terminalCode}`;const attemptKey=`${storageKey}.allocation-attempt`;
 useEffect(()=>{void apiRequest<{rules:{cardManualEnabled:boolean;integratedCardEnabled:boolean};providerDescriptors:Array<{provider:string;capabilities:string[]}>;configuration:{provider:string;enabled:boolean}}>("/terminal-configuration/payment",{token}).then(c=>{setManual(c.rules.cardManualEnabled);setProviders(c.rules.integratedCardEnabled&&c.configuration.enabled?[c.configuration.provider]:[]);setCapabilities(c.providerDescriptors.find(p=>p.provider===c.configuration.provider)?.capabilities??[]);}).catch(()=>{});},[token]);
 useEffect(()=>{let current=true;entryHydratedSessionIdRef.current=null;setHydrationComplete(false);void (async()=>{try{const active=await apiRequest<ServerSession|null>("/pos/payment-sessions/active",{token});if(current){if(active){entryHydratedSessionIdRef.current=active.id;setServer(active);globalThis.sessionStorage?.setItem(storageKey,active.id);}else{globalThis.sessionStorage?.removeItem(storageKey);globalThis.localStorage?.removeItem(attemptKey);}setHydrationComplete(true);}}catch{const id=globalThis.sessionStorage?.getItem(storageKey);if(id)try{const recovered=await apiRequest<ServerSession>(`/pos/payment-sessions/${id}`,{token});if(current){entryHydratedSessionIdRef.current=recovered.id;setServer(recovered);setHydrationComplete(true);}}catch{/* Recovery remains authoritative only after a successful response. */}}})();return()=>{current=false;};},[storageKey,attemptKey,token]);
 useEffect(()=>onLockedChange?.(paymentSessionLocksSale(server?.status),server?Math.round(Number(server.total)*100):undefined),[server,onLockedChange]);
 function clearRecoveredSession(){globalThis.sessionStorage?.removeItem(storageKey);globalThis.localStorage?.removeItem(attemptKey);cashAttemptRef.current=null;cashGuardRef.current=false;cardGuardRef.current=false;exitFeedbackRef.current=null;setCashOpen(false);setManualCardOpen(false);setCompensationDialog(false);setCompensationNote("");setAuthorization(null);setAuthorizationPassword("");setOperation(null);setEvents([]);setSafeRetry(false);setTestCashRequired(false);setTestCashStatus("");setError("");setServer(null);}
 async function ensure(){if(server)return server;const id=uuid();const created=await apiRequest<ServerSession>("/pos/payment-sessions",{token,body:{sessionId:id,sale}});globalThis.sessionStorage?.setItem(storageKey,created.id);setServer(created);return created;}
 async function finish(next:ServerSession,cashAttempt?:CashAttemptMetadata){if(next.status!=="COVERED")return;const done=await apiRequest<ServerSession>(`/pos/payment-sessions/${next.id}/finalize`,{token,method:"POST"});setServer(paymentSessionAfterFinalization(done.ticketNumber,done));if(done.ticketNumber){globalThis.sessionStorage?.removeItem(storageKey);globalThis.localStorage?.removeItem(attemptKey);setCashOpen(false);setManualCardOpen(false);setTestCashRequired(false);setTestCashStatus("");setError("");const receivedCents=cashAttempt?.sessionId===done.id?cashAttempt.receivedCents:undefined;if(cashAttemptRef.current?.sessionId===done.id)cashAttemptRef.current=null;cashGuardRef.current=false;cardGuardRef.current=false;onFinalized(done.ticketNumber,Math.round(Number(done.total)*100),receivedCents);}}
 function markTestCashRequirement(failure:unknown){const required=testCashEnabled&&failure instanceof ApiError&&isMissingCashSessionError(failure.message);setTestCashRequired(required);setTestCashStatus("");}
 async function openTestCashSession(){if(!testCashEnabled||!terminal.terminalId||busy)return;setBusy(true);setTestCashStatus("");try{await apiRequest("/cash/sessions/open",{token,body:{terminalId:terminal.terminalId}});setError("");setTestCashRequired(false);setTestCashStatus(t("payment.testCash.opened"));}catch(failure){setError(failure instanceof ApiError?failure.message:t("payment.testCash.error"));}finally{setBusy(false);}}
 async function retryFinish(){if(!server||server.status!=="COVERED")return;setBusy(true);setError("");const cashAttempt=cashAttemptRef.current?.sessionId===server.id?cashAttemptRef.current:undefined;try{await finish(server,cashAttempt);}catch(e){markTestCashRequirement(e);setError(e instanceof ApiError?e.message:t("payment.split.error.finalize"));}finally{setBusy(false);}}
 async function add(input:{kind:string;amountCents:number;provider?:string;reference?:string},cashAttempt?:CashAttemptMetadata){setBusy(true);setError("");setSafeRetry(false);let s:ServerSession|undefined;let allocationAccepted=false;try{s=await ensure();if(cashAttempt){cashAttempt.sessionId=s.id;cashAttemptRef.current=cashAttempt;}const recoveryInput={kind:input.kind,amountCents:input.amountCents,...(input.provider?{provider:input.provider}:{})};const stored=globalThis.localStorage?.getItem(attemptKey);const parsed=stored?JSON.parse(stored) as {sessionId:string;allocationId:string;input:typeof recoveryInput}:null;const attempt=stableAllocationAttempt(parsed,s.id,recoveryInput,uuid);const allocationId=attempt.allocationId;globalThis.localStorage?.setItem(attemptKey,JSON.stringify(attempt));const next=await apiRequest<ServerSession>(`/pos/payment-sessions/${s.id}/allocations`,{token,body:{allocationId,idempotencyKey:allocationId,kind:input.kind,amount:(input.amountCents/100).toFixed(2),provider:input.provider,reference:input.reference}});allocationAccepted=true;setServer(next);const allocationStatus=next.allocations.find(a=>a.id===allocationId)?.status;const safeTerminal=allocationStatus==="DECLINED"||allocationStatus==="ERROR";if(safeTerminal){globalThis.localStorage?.removeItem(attemptKey);if(input.kind==="CASH"){cashAttemptRef.current=null;cashGuardRef.current=false;setCashOpen(false);}else{cardGuardRef.current=false;setManualCardOpen(false);}}else if(next.status!=="COVERED"&&!next.allocations.some(a=>a.id===allocationId&&(a.status==="PENDING"||a.status==="TIMEOUT")))globalThis.localStorage?.removeItem(attemptKey);await finish(next,cashAttempt);}catch(e){markTestCashRequirement(e);if(!allocationAccepted&&e instanceof ApiError&&allocationFailureIsSafePreEffect(e)){globalThis.localStorage?.removeItem(attemptKey);if(cashAttemptRef.current===cashAttempt)cashAttemptRef.current=null;if(cashAttempt)cashGuardRef.current=false;if(input.kind==="MANUAL_CARD"||input.kind==="INTEGRATED_CARD")cardGuardRef.current=false;setSafeRetry(true);setError(e.message);}else{setError(e instanceof ApiError?`${e.message}. ${t("payment.split.error.uncertainSame")}`:t("payment.split.error.uncertain"));if(s&&!(allocationAccepted&&e instanceof ApiError&&e.status===409&&isMissingCashSessionError(e.message)))void apiRequest<ServerSession>("/pos/payment-sessions/active",{token}).then(active=>setServer(active)).catch(()=>{});}}finally{setBusy(false);}}
 function confirmCash(receivedCents:number){if(cashGuardRef.current)return;cashGuardRef.current=true;const cashAttempt={receivedCents};cashAttemptRef.current=cashAttempt;void add({kind:"CASH",amountCents:totalCents},cashAttempt);}
 function startCard(){if(cardGuardRef.current)return;if(providers[0]){cardGuardRef.current=true;void add({kind:"INTEGRATED_CARD",amountCents:totalCents,provider:providers[0]});}else if(manual){setManualCardOpen(true);}}
 function confirmManualCard(reference:string){if(cardGuardRef.current)return;cardGuardRef.current=true;setManualCardOpen(false);void add({kind:"MANUAL_CARD",amountCents:totalCents,reference});}
 async function query(allocationId:string){if(!server)return;setBusy(true);setError("");const queried=server.allocations.find(a=>a.id===allocationId||a.operationId===allocationId);const cashAttempt=queried?.kind==="CASH"&&cashAttemptRef.current?.sessionId===server.id?cashAttemptRef.current:undefined;try{const next=await apiRequest<ServerSession>(`/pos/payment-sessions/${server.id}/allocations/${allocationId}/query`,{token,method:"POST"});setServer(next);const resolved=next.allocations.find(a=>a.id===allocationId||a.operationId===allocationId);const safeTerminal=resolved?.status==="DECLINED"||resolved?.status==="ERROR";if(safeTerminal){globalThis.localStorage?.removeItem(attemptKey);if(resolved.kind==="CASH"){cashAttemptRef.current=null;cashGuardRef.current=false;setCashOpen(false);}else{cardGuardRef.current=false;setManualCardOpen(false);}}else if(next.status!=="COVERED"&&!(resolved?.status==="PENDING"||resolved?.status==="TIMEOUT"))globalThis.localStorage?.removeItem(attemptKey);await finish(next,cashAttempt);}catch(e){setError(e instanceof ApiError?e.message:t("payment.split.error.query"));}finally{setBusy(false);}}
 async function cancel():Promise<CancellationResult>{if(!server)return "NOT_CANCELLED";setBusy(true);try{const next=await apiRequest<ServerSession>(`/pos/payment-sessions/${server.id}/cancel`,{token,method:"POST"});setServer(next);if(next.status==="CANCELLED"){clearRecoveredSession();return "CANCELLED";}setError(t("payment.split.error.cancelCompensation"));return "NOT_CANCELLED";}catch(e){setError(e instanceof ApiError?e.message:t("payment.split.error.cancel"));return "ERROR";}finally{setBusy(false);}}
 async function discardSimulator(reason:"application_shutdown"|"sale_entry_cleanup",feedbackKey:"payment.pending.logoutError"|"payment.pending.shutdownBlocked"|"payment.pending.simulatorCleanupError"){if(!server)return false;setBusy(true);try{const next=await apiRequest<ServerSession>(`/pos/payment-sessions/${server.id}/simulator-discard`,{token,body:{reason}});setServer(next);if(next.status==="CANCELLED"){clearRecoveredSession();return true;}setError(t(feedbackKey==="payment.pending.simulatorCleanupError"?(exitFeedbackRef.current??feedbackKey):feedbackKey));return false;}catch{setError(t(feedbackKey==="payment.pending.simulatorCleanupError"?(exitFeedbackRef.current??feedbackKey):feedbackKey));return false;}finally{setBusy(false);}}
 function cleanupSingleFlight(sessionId:string,operation:()=>Promise<boolean>){const current=cleanupFlightRef.current;if(current?.sessionId===sessionId)return current.promise;const promise=operation().finally(()=>{if(cleanupFlightRef.current?.promise===promise)cleanupFlightRef.current=null;});cleanupFlightRef.current={sessionId,promise};return promise;}
 async function prepareExit(feedbackKey:"payment.pending.logoutError"|"payment.pending.shutdownBlocked"){exitFeedbackRef.current=feedbackKey;const disposition=paymentLogoutDisposition(server,hydrationComplete);if(disposition==="READY"){clearRecoveredSession();return "READY" as const;}if(!server){setError(t(feedbackKey));return "BLOCKED" as const;}const cleaned=await cleanupSingleFlight(server.id,disposition==="AUTO_CANCEL"?async()=>await cancel()==="CANCELLED":()=>discardSimulator("application_shutdown",feedbackKey));if(cleaned)return "READY" as const;setError(t(feedbackKey));return "BLOCKED" as const;}
 useImperativeHandle(ref,()=>({prepareLogout:()=>prepareExit("payment.pending.logoutError"),prepareApplicationClose:()=>prepareExit("payment.pending.shutdownBlocked")}));
 useEffect(()=>{if(!hydrationComplete||!server||entryHydratedSessionIdRef.current!==server.id||paymentLogoutDisposition(server,true)==="READY"||entryCleanupAttempted.has(server.id))return;entryCleanupAttempted.add(server.id);void cleanupSingleFlight(server.id,()=>discardSimulator("sale_entry_cleanup","payment.pending.simulatorCleanupError"));},[hydrationComplete,server?.id]);
 async function acknowledge(){if(!server||!compensationNote.trim())return;setCompensationDialog(false);setBusy(true);await compensationNoteIsEphemeral(compensationNote,setCompensationNote,async note=>{try{const next=await apiRequest<ServerSession>(`/pos/payment-sessions/${server.id}/compensation-ack`,{token,body:{note}});setServer(next);if(next.status==="CANCELLED")clearRecoveredSession();}catch(e){setError(e instanceof ApiError?e.message:t("payment.split.error.acknowledge"));}finally{setBusy(false);}});}
 async function manage(id:string){setBusy(true);try{const [op,history]=await Promise.all([apiRequest<PaymentOperationView>(`/payment-terminal/operations/${id}`,{token}),loadPaymentOperationHistory(id,token)]);setOperation(op);setEvents(history);}catch(e){setError(e instanceof ApiError?e.message:t("payment.split.error.loadOperation"));}finally{setBusy(false);}}
 async function authorize(){if(!authorization||!operation||!authorizationPassword)return;const action=authorization;setAuthorization(null);await authorizationPasswordIsEphemeral(authorizationPassword,setAuthorizationPassword,async password=>{try{const next=action.kind==="VOID"?await voidPaymentOperation(operation.id,token,password,uuid()):await refundPaymentOperation(operation.id,token,action.amount,password,uuid());setOperation(next);}catch(e){setError(e instanceof ApiError?e.message:t(action.kind==="VOID"?"payment.split.error.void":"payment.split.error.refund"));}});}
 const cancelCashDialog=()=>{if(cashGuardRef.current)return;cashAttemptRef.current=null;setCashOpen(false);};
 const testCashOffered=shouldOfferTestCashSession(testCashEnabled,server?.status,testCashRequired,terminal.terminalId);
 const cashDialog=cashOpen?<CashPaymentDialog totalCents={totalCents} submitting={busy} error={error} initialMode="touch" onCancel={cancelCashDialog} onConfirm={server?.status==="COVERED"?()=>void retryFinish():confirmCash} testCashAction={testCashOffered?{label:busy?t("payment.testCash.opening"):t("payment.testCash.open"),onOpen:()=>void openTestCashSession()}:undefined} testCashStatus={testCashStatus}/>:null;
 const manualCardDialog=manualCardOpen?<div className="sale-action-overlay manual-card-payment-overlay"><div className="manual-card-payment-dialog"><ManualCardReferenceDialog busy={busy} onCancel={()=>setManualCardOpen(false)} onConfirm={confirmManualCard}/></div></div>:null;
 const presentation=checkoutPresentation(server?.status,server?.allocations.map(allocation=>allocation.status),safeRetry);
 if(presentation==="INDIVIDUAL_ACTIONS")return <><IndividualPaymentActions disabled={!!disabled||totalCents<=0} busy={busy} cardEnabled={manual||providers.length>0} onCash={()=>setCashOpen(true)} onCard={startCard}/>{cashDialog}{manualCardDialog}{error&&!cashOpen&&<p role="alert">{error}</p>}</>;
 if(presentation==="FINALIZE_RETRY")return <><div aria-busy={busy}><PaymentAllocationPanel locale={locale} session={map(server!)} providers={providers} manualCardEnabled={manual} onAdd={input=>void add(input)} onQuery={id=>void query(id)} onManage={id=>void manage(id)}/><button type="button" disabled={!canManuallyFinalizePayment(server!.status,busy)} onClick={()=>void retryFinish()}>{t("payment.split.finalize")}</button><button type="button" disabled={busy} onClick={()=>void cancel()}>{t("payment.split.cancelSession")}</button>{error&&<p role="alert">{error}</p>}{testCashStatus&&<p className="test-cash-session-status" role="status">{testCashStatus}</p>}{shouldOfferTestCashSession(testCashEnabled,server!.status,testCashRequired,terminal.terminalId)&&<button className="test-cash-session-button" type="button" disabled={busy} onClick={()=>void openTestCashSession()}>{busy?t("payment.testCash.opening"):t("payment.testCash.open")}</button>}</div>{cashDialog}</>;
 if(!server)return null;
 return <><div aria-busy={busy}><PaymentAllocationPanel locale={locale} session={map(server)} providers={providers} manualCardEnabled={manual} onAdd={input=>void add(input)} onQuery={id=>void query(id)} onManage={id=>void manage(id)} allowAdd={presentation!=="RECOVERY"}/><button type="button" disabled={busy} onClick={()=>void cancel()}>{t("payment.split.cancelSession")}</button>{server.status==="COMPENSATION_REQUIRED"&&<div role="alert"><p>{t("payment.split.compensationGuidance")}</p>{(permissions.includes("ADMIN")||permissions.includes("PAYMENT_TERMINAL_REFUND"))&&<button type="button" onClick={()=>{setCompensationNote("");setCompensationDialog(true);}}>{t("payment.split.acknowledge")}</button>}</div>}{compensationDialog&&<div role="dialog" aria-modal="true" aria-label={t("payment.split.compensationDialogTitle")}><h3>{t("payment.split.compensationDialogTitle")}</h3><label>{t("payment.split.compensationNote")}<textarea value={compensationNote} onChange={e=>setCompensationNote(e.currentTarget.value)} autoComplete="off"/></label><button type="button" disabled={!compensationNote.trim()} onClick={()=>void acknowledge()}>{t("payment.split.confirm")}</button><button type="button" onClick={()=>{setCompensationNote("");setCompensationDialog(false);}}>{t("payment.split.cancel")}</button></div>}{operation&&<PaymentOperationPanel operation={operation} events={events} capabilities={capabilities} permissions={permissions} onQuery={()=>void queryPaymentOperation(operation.id,token).then(setOperation).catch(e=>setError(e instanceof ApiError?e.message:t("payment.split.error.operationQuery")))} onVoid={()=>{setAuthorizationPassword("");setAuthorization({kind:"VOID",amount:""});}} onRefund={()=>{setAuthorizationPassword("");setAuthorization({kind:"REFUND",amount:""});}} onPrintReceipt={()=>void printPaymentReceipt(operation.id,token,terminal,getHardwareBridge()).catch(e=>setError(e instanceof ApiError?e.message:t("payment.split.error.print")))}/>} {authorization&&<div role="dialog" aria-modal="true" aria-label={t(`payment.split.authorizationTitle.${authorization.kind}`)}><h3>{t(`payment.split.authorizationTitle.${authorization.kind}`)}</h3>{authorization.kind==="REFUND"&&<label>{t("payment.split.refundAmount")}<input inputMode="decimal" value={authorization.amount} onChange={e=>setAuthorization({...authorization,amount:e.currentTarget.value})}/></label>}<label>{t("payment.split.authorizationPassword")}<input type="password" autoComplete="current-password" value={authorizationPassword} onChange={e=>setAuthorizationPassword(e.currentTarget.value)}/></label><button type="button" onClick={()=>void authorize()} disabled={!authorizationPassword||(authorization.kind==="REFUND"&&!authorization.amount)}>{t("payment.split.confirm")}</button><button type="button" onClick={()=>{setAuthorizationPassword("");setAuthorization(null);}}>{t("payment.split.cancel")}</button></div>}{error&&<p role="alert">{error}</p>}</div>{cashDialog}</>;
});
