import { useEffect, useState } from "react";
import { apiRequest, ApiError } from "../api/client";
import { PaymentAllocationPanel } from "./PaymentAllocationPanel";
import type { PaymentSession } from "../sale/paymentOrchestration";
import { PaymentOperationPanel, type PaymentOperationEvent, type PaymentOperationView } from "./PaymentOperationPanel";
import { getHardwareBridge } from "../hardware/hardware";
import { loadPaymentOperationHistory, printPaymentReceipt, queryPaymentOperation, refundPaymentOperation, voidPaymentOperation } from "../sale/paymentOperations";
import type { Permission, TerminalContext } from "../types";

type Sale = { customerId: string | null; lines: Array<{ productId: string; quantity: number; discount: number }> };
type ServerSession = { id: string; total: number | string; status: string; ticketId?: string; ticketNumber?: string; allocations: Array<{ id: string; idempotencyKey: string; kind: "CASH"|"MANUAL_CARD"|"INTEGRATED_CARD"; amount: number|string; provider?: string; operationId?: string; status: string; reference?: string; authorization?: string; message?: string }> };
type Props = { totalCents: number; sale: Sale; token?: string; permissions: Permission[]; terminal: TerminalContext; disabled?: boolean; onLockedChange?: (locked:boolean)=>void; onFinalized: (ticketNumber: string,totalCents:number) => void };
const uuid=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random()}`;
const map=(s:ServerSession):PaymentSession=>({id:s.id,totalCents:Math.round(Number(s.total)*100),status:s.status==="COVERED"||s.status==="FINALIZED"?"COVERED":"COLLECTING",allocations:s.allocations.map(a=>({...a,amountCents:Math.round(Number(a.amount)*100),status:a.status as never}))});
export const compensationGuidance="Compensación obligatoria: los pagos aprobados siguen visibles. Anula/reembolsa tarjetas desde Gestionar operación y registra la resolución administrativa de efectivo o tarjeta manual.";
export function paymentSessionLocksSale(status:string|null|undefined){return !!status&&status!=="FINALIZED"&&status!=="CANCELLED";}
export function stableAllocationAttempt<T>(stored:{sessionId:string;allocationId:string;input:T}|null,sessionId:string,input:T,generate:()=>string){return stored?.sessionId===sessionId&&JSON.stringify(stored.input)===JSON.stringify(input)?stored:{sessionId,allocationId:generate(),input};}
export function allocationFailureIsSafePreEffect(error:ApiError){return [400,401,403,404,409,422].includes(error.status);}

export function SalePaymentCheckout({totalCents,sale,token,permissions,terminal,disabled,onLockedChange,onFinalized}:Props){
 const [server,setServer]=useState<ServerSession|null>(null);const [providers,setProviders]=useState<string[]>([]);const [capabilities,setCapabilities]=useState<string[]>([]);const [manual,setManual]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [operation,setOperation]=useState<PaymentOperationView|null>(null);const [events,setEvents]=useState<PaymentOperationEvent[]>([]);
 const storageKey=`tpverp.payment-session.${terminal.terminalId??terminal.terminalCode}`;
 const attemptKey=`${storageKey}.allocation-attempt`;
 useEffect(()=>{void apiRequest<{rules:{cardManualEnabled:boolean;integratedCardEnabled:boolean};providerDescriptors:Array<{provider:string;capabilities:string[]}>;configuration:{provider:string;enabled:boolean}}>("/terminal-configuration/payment",{token}).then(c=>{setManual(c.rules.cardManualEnabled);setProviders(c.rules.integratedCardEnabled&&c.configuration.enabled?[c.configuration.provider]:[]);setCapabilities(c.providerDescriptors.find(p=>p.provider===c.configuration.provider)?.capabilities??[]);}).catch(()=>{});},[token]);
 useEffect(()=>{void apiRequest<ServerSession|null>("/pos/payment-sessions/active",{token}).then(s=>{if(s){setServer(s);globalThis.sessionStorage?.setItem(storageKey,s.id);}}).catch(()=>{const id=globalThis.sessionStorage?.getItem(storageKey);if(id)void apiRequest<ServerSession>(`/pos/payment-sessions/${id}`,{token}).then(setServer).catch(()=>globalThis.sessionStorage?.removeItem(storageKey));});},[storageKey,token]);
 useEffect(()=>onLockedChange?.(paymentSessionLocksSale(server?.status)),[server,onLockedChange]);
 async function ensure(){if(server)return server;const id=uuid();const created=await apiRequest<ServerSession>("/pos/payment-sessions",{token,body:{sessionId:id,sale}});globalThis.sessionStorage?.setItem(storageKey,created.id);setServer(created);return created;}
 async function finish(next:ServerSession){if(next.status!=="COVERED")return;const done=await apiRequest<ServerSession>(`/pos/payment-sessions/${next.id}/finalize`,{token,method:"POST"});setServer(done);if(done.ticketNumber){globalThis.sessionStorage?.removeItem(storageKey);onFinalized(done.ticketNumber,Math.round(Number(done.total)*100));}}
 async function add(input:{kind:string;amountCents:number;provider?:string;reference?:string}){setBusy(true);setError("");let s:ServerSession|undefined;try{s=await ensure();const stored=globalThis.localStorage?.getItem(attemptKey);const parsed=stored?JSON.parse(stored) as {sessionId:string;allocationId:string;input:typeof input}:null;const attempt=stableAllocationAttempt(parsed,s.id,input,uuid);const allocationId=attempt.allocationId;globalThis.localStorage?.setItem(attemptKey,JSON.stringify(attempt));const next=await apiRequest<ServerSession>(`/pos/payment-sessions/${s.id}/allocations`,{token,body:{allocationId,idempotencyKey:allocationId,kind:input.kind,amount:(input.amountCents/100).toFixed(2),provider:input.provider,reference:input.reference}});setServer(next);if(!next.allocations.some(a=>a.id===allocationId&&(a.status==="PENDING"||a.status==="TIMEOUT")))globalThis.localStorage?.removeItem(attemptKey);await finish(next);}catch(e){if(e instanceof ApiError&&allocationFailureIsSafePreEffect(e)){globalThis.localStorage?.removeItem(attemptKey);setError(e.message);}else{setError(e instanceof ApiError?`${e.message}. Se conserva el mismo intento hasta confirmar el estado.`:"Resultado incierto; se conserva el mismo intento. Consulta o reintenta sin crear otro cargo.");if(s)void apiRequest<ServerSession>("/pos/payment-sessions/active",{token}).then(active=>setServer(active)).catch(()=>{});}}finally{setBusy(false);}}
 async function query(allocationId:string){if(!server)return;setBusy(true);try{const next=await apiRequest<ServerSession>(`/pos/payment-sessions/${server.id}/allocations/${allocationId}/query`,{token,method:"POST"});setServer(next);if(!next.allocations.some(a=>a.id===allocationId&&(a.status==="PENDING"||a.status==="TIMEOUT")))globalThis.localStorage?.removeItem(attemptKey);await finish(next);}catch(e){setError(e instanceof ApiError?e.message:"No se pudo consultar; la operación permanece pendiente");}finally{setBusy(false);}}
 async function cancel(){if(!server)return;setBusy(true);try{const next=await apiRequest<ServerSession>(`/pos/payment-sessions/${server.id}/cancel`,{token,method:"POST"});setServer(next);if(next.status==="CANCELLED"){globalThis.sessionStorage?.removeItem(storageKey);setServer(null);}else setError("Hay pagos aprobados: requiere compensación. Gestiona void/refund de tarjeta; efectivo/manual requieren resolución administrativa autorizada.");}catch(e){setError(e instanceof ApiError?e.message:"No se pudo cancelar");}finally{setBusy(false);}}
 async function acknowledge(){if(!server)return;const note=globalThis.prompt?.("Describe la resolución administrativa de efectivo/tarjeta manual")?.trim();if(!note)return;setBusy(true);try{const next=await apiRequest<ServerSession>(`/pos/payment-sessions/${server.id}/compensation-ack`,{token,body:{note}});setServer(next);globalThis.sessionStorage?.removeItem(storageKey);if(next.status==="CANCELLED")setServer(null);}catch(e){setError(e instanceof ApiError?e.message:"No se pudo registrar la resolución");}finally{setBusy(false);}}
 async function manage(id:string){setBusy(true);try{const [op,history]=await Promise.all([apiRequest<PaymentOperationView>(`/payment-terminal/operations/${id}`,{token}),loadPaymentOperationHistory(id,token)]);setOperation(op);setEvents(history);}catch(e){setError(e instanceof ApiError?e.message:"No se pudo cargar la operación");}finally{setBusy(false);}}
 if(!server)return <button type="button" disabled={disabled||busy||totalCents<=0} onClick={()=>void ensure().catch(e=>setError(e instanceof Error?e.message:"No se pudo iniciar el cobro"))}>Iniciar cobro dividido</button>;
 return <div aria-busy={busy}><PaymentAllocationPanel session={map(server)} providers={providers} manualCardEnabled={manual} onAdd={input=>void add(input)} onQuery={id=>void query(id)} onManage={id=>void manage(id)}/><button type="button" disabled={busy} onClick={()=>void cancel()}>Cancelar sesión de cobro</button>{server.status==="COMPENSATION_REQUIRED"&&<div role="alert"><p>{compensationGuidance}</p>{(permissions.includes("ADMIN")||permissions.includes("PAYMENT_TERMINAL_REFUND"))&&<button type="button" onClick={()=>void acknowledge()}>Registrar resolución administrativa</button>}</div>}{operation&&<PaymentOperationPanel operation={operation} events={events} capabilities={capabilities} permissions={permissions} onQuery={()=>void queryPaymentOperation(operation.id,token).then(setOperation).catch(e=>setError(e instanceof ApiError?e.message:"No se pudo consultar"))} onVoid={()=>{const password=globalThis.prompt?.("Contraseña de autorización")??"";void voidPaymentOperation(operation.id,token,password,uuid()).then(setOperation).catch(e=>setError(e instanceof ApiError?e.message:"No se pudo anular"));}} onRefund={()=>{const amount=globalThis.prompt?.("Importe a reembolsar")??"";const password=globalThis.prompt?.("Contraseña de autorización")??"";void refundPaymentOperation(operation.id,token,amount,password,uuid()).then(setOperation).catch(e=>setError(e instanceof ApiError?e.message:"No se pudo reembolsar"));}} onPrintReceipt={()=>void printPaymentReceipt(operation.id,token,terminal,getHardwareBridge()).catch(e=>setError(e instanceof ApiError?e.message:"No se pudo imprimir"))}/>} {error&&<p role="alert">{error}</p>}</div>;
}
