package com.tpverp.backend.terminal;

import java.util.EnumSet;
import java.util.Locale;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

abstract class DeterministicPaymentTerminalSimulator implements CardTerminalGateway {
    private final PaymentTerminalProvider provider;
    private final ConcurrentMap<UUID, PaymentTerminalResult> operations = new ConcurrentHashMap<>();
    DeterministicPaymentTerminalSimulator(PaymentTerminalProvider provider) { this.provider=provider; }

    @Override public boolean supports(PaymentTerminalProvider candidate,boolean testMode){ return candidate==provider && testMode; }
    @Override public Set<PaymentTerminalCapability> capabilities(){ return Set.copyOf(EnumSet.allOf(PaymentTerminalCapability.class)); }
    @Override public PaymentTerminalResult pair(PaymentTerminalPairCommand command,PaymentTerminalGatewayContext context){ validate(context); return result(PaymentTerminalOperationStatus.APPROVED,"PAIRED",id(command.pairingId()),null,"Emparejamiento simulado completado"); }
    @Override public PaymentTerminalResult pairingStatus(PaymentTerminalPairCommand command,PaymentTerminalGatewayContext context){ validate(context); return result(PaymentTerminalOperationStatus.APPROVED,"PAIRED",id(command.pairingId()),null,"Datáfono simulado emparejado"); }
    @Override public PaymentTerminalResult charge(PaymentTerminalChargeCommand command,PaymentTerminalGatewayContext context){ validate(context); return operations.computeIfAbsent(command.operationId(), ignored -> configured(context,command.operationId(),true,"simulatorOutcome")); }
    @Override public PaymentTerminalResult query(PaymentTerminalQueryCommand command,PaymentTerminalGatewayContext context){ validate(context); var stored=operations.get(command.operationId()); if(stored==null)return result(PaymentTerminalOperationStatus.ERROR,"OPERATION_NOT_FOUND",id(command.operationId()),null,"Operación simulada no encontrada"); if(stored.status()!=PaymentTerminalOperationStatus.PENDING&&stored.status()!=PaymentTerminalOperationStatus.TIMEOUT)return stored; var queryOutcome=context.parameters().get("simulatorQueryOutcome"); if(queryOutcome==null)return stored; var resolved=configured(context,command.operationId(),true,"simulatorQueryOutcome"); operations.put(command.operationId(),resolved); return resolved; }
    @Override public PaymentTerminalResult voidAuthorization(PaymentTerminalVoidCommand command,PaymentTerminalGatewayContext context){ validate(context); return result(PaymentTerminalOperationStatus.CANCELLED,"VOIDED",id(command.operationId()),null,"Autorización simulada anulada"); }
    @Override public PaymentTerminalResult refund(PaymentTerminalRefundCommand command,PaymentTerminalGatewayContext context){ validate(context); return result(PaymentTerminalOperationStatus.PARTIALLY_REFUNDED,"PARTIAL_REFUND",id(command.operationId()),id(command.operationId()).substring(0,8),"Devolución parcial simulada aprobada"); }
    @Override public PaymentTerminalReceipt receipt(PaymentTerminalReceiptCommand command,PaymentTerminalGatewayContext context){ validate(context); return new PaymentTerminalReceipt(provider.name()+"\nREFERENCIA "+safe(command.reference())+"\nOPERACIÓN "+command.operationId()); }
    @Override public PaymentTerminalResult reconcile(PaymentTerminalReconciliationCommand command,PaymentTerminalGatewayContext context){ validate(context); return result(PaymentTerminalOperationStatus.APPROVED,"RECONCILED",id(command.reconciliationId()),null,"Conciliación simulada completada"); }

    @Override public CardTerminalResult testConnection(CardTerminalConfiguration configuration){ var diagnostic=legacyDiagnostic(configuration); if(diagnostic!=null)return legacyError(diagnostic); return legacy(outcome(configuration.parameters().get("simulatorOutcome")),UUID.randomUUID()); }
    @Override public CardTerminalResult charge(CardTerminalRequest request,CardTerminalConfiguration configuration){ var diagnostic=legacyDiagnostic(configuration); if(diagnostic!=null)return legacyError(diagnostic); if(request.provider()!=provider)return legacyError("Proveedor de la solicitud no compatible"); if(!request.terminalId().equals(configuration.terminalId()))return legacyError("La solicitud no corresponde al terminal configurado"); return legacy(outcome(configuration.parameters().get("simulatorOutcome")),request.checkoutId()); }

    private void validate(PaymentTerminalGatewayContext context){ if(context.provider()!=provider)throw new IllegalArgumentException("provider mismatch"); if(context.mode()!=PaymentTerminalMode.SIMULATED)throw new IllegalArgumentException("simulated mode required"); }
    private PaymentTerminalResult configured(PaymentTerminalGatewayContext context,UUID id,boolean authorization,String parameter){ var status=outcome(context.parameters().get(parameter)); return result(status,code(status),id(id),status==PaymentTerminalOperationStatus.APPROVED&&authorization?id(id).substring(0,8):null,message(status)); }
    private PaymentTerminalOperationStatus outcome(String value){ if(value==null)return PaymentTerminalOperationStatus.ERROR; return switch(value.trim().toUpperCase(Locale.ROOT)){ case "PENDING"->PaymentTerminalOperationStatus.PENDING; case "SENT"->PaymentTerminalOperationStatus.SENT; case "APPROVED"->PaymentTerminalOperationStatus.APPROVED; case "DECLINED"->PaymentTerminalOperationStatus.DECLINED; case "CANCELLED"->PaymentTerminalOperationStatus.CANCELLED; case "REFUNDED"->PaymentTerminalOperationStatus.REFUNDED; case "PARTIALLY_REFUNDED"->PaymentTerminalOperationStatus.PARTIALLY_REFUNDED; case "TIMEOUT"->PaymentTerminalOperationStatus.TIMEOUT; case "REVIEW_REQUIRED"->PaymentTerminalOperationStatus.REVIEW_REQUIRED; case "ERROR","CONNECTION_ERROR"->PaymentTerminalOperationStatus.ERROR; default->PaymentTerminalOperationStatus.ERROR; }; }
    private String legacyDiagnostic(CardTerminalConfiguration c){ if(!c.enabled())return "Configuración de datáfono desactivada"; if(c.mode()!=PaymentCardMode.INTEGRATED)return "El datáfono requiere modo integrado"; if(c.provider()!=provider)return "El proveedor configurado no es "+provider; if(!c.testMode())return "Conector SDK "+provider+" no disponible fuera del modo de pruebas"; return null; }
    private CardTerminalResult legacy(PaymentTerminalOperationStatus status,UUID operation){ var operationId=id(operation); return new CardTerminalResult(status,"SIM-"+operationId,status==PaymentTerminalOperationStatus.APPROVED?"SIMAUTH-"+operationId.substring(0,8):null,message(status)); }
    private CardTerminalResult legacyError(String message){ return new CardTerminalResult(PaymentTerminalOperationStatus.ERROR,null,null,message); }
    private PaymentTerminalResult result(PaymentTerminalOperationStatus status,String code,String reference,String authorization,String message){ return new PaymentTerminalResult(status,code,provider.name()+"-SIM-"+reference,authorization==null?null:provider.name()+"-SIMAUTH-"+authorization,message); }
    private String id(UUID id){ return id.toString().replace("-","").toUpperCase(Locale.ROOT); }
    private String code(PaymentTerminalOperationStatus s){ return switch(s){ case PENDING->"PENDING"; case SENT->"SENT"; case APPROVED->"APPROVED"; case DECLINED->"DECLINED"; case CANCELLED->"CANCELLED"; case REFUNDED->"REFUNDED"; case PARTIALLY_REFUNDED->"PARTIALLY_REFUNDED"; case TIMEOUT->"TIMEOUT"; case REVIEW_REQUIRED->"REVIEW_REQUIRED"; case ERROR->"SIMULATOR_ERROR"; }; }
    private String message(PaymentTerminalOperationStatus s){ return switch(s){ case PENDING->"Operación simulada pendiente"; case SENT->"Operación simulada enviada"; case APPROVED->"Operación simulada aprobada"; case DECLINED->"Operación simulada rechazada"; case CANCELLED->"Operación simulada cancelada"; case REFUNDED->"Operación simulada devuelta"; case PARTIALLY_REFUNDED->"Operación simulada parcialmente devuelta"; case TIMEOUT->"Tiempo de espera agotado en el simulador"; case REVIEW_REQUIRED->"Operación simulada pendiente de revisión"; case ERROR->"Error de conexión con el simulador"; }; }
    private String safe(String value){ return value.replaceAll("[^A-Za-z0-9._-]","").substring(0,Math.min(64,value.replaceAll("[^A-Za-z0-9._-]","").length())); }
}
