package com.tpverp.backend.terminal;

import java.util.*;
import java.util.concurrent.*;

abstract class DeterministicPaymentTerminalSimulator implements CardTerminalGateway {
 private final PaymentTerminalProvider provider;private final ConcurrentMap<UUID,PaymentTerminalResult> operations=new ConcurrentHashMap<>();private final ConcurrentMap<UUID,PaymentTerminalResult> pairings=new ConcurrentHashMap<>();
 DeterministicPaymentTerminalSimulator(PaymentTerminalProvider provider){this.provider=provider;}
 @Override public boolean supports(PaymentTerminalProvider candidate,boolean testMode){return candidate==provider&&testMode;}
 @Override public Set<PaymentTerminalCapability> capabilities(){return Set.copyOf(EnumSet.allOf(PaymentTerminalCapability.class));}
 @Override public PaymentTerminalResult pair(PaymentTerminalPairCommand c,PaymentTerminalGatewayContext x){validate(x);return pairings.computeIfAbsent(c.pairingId(),id->result(PaymentTerminalOperationStatus.APPROVED,"PAIRED",id(id),null,"Emparejamiento simulado completado"));}
 @Override public PaymentTerminalResult pairingStatus(PaymentTerminalPairCommand c,PaymentTerminalGatewayContext x){validate(x);return pairings.getOrDefault(c.pairingId(),result(PaymentTerminalOperationStatus.ERROR,"PAIRING_NOT_FOUND",id(c.pairingId()),null,"Emparejamiento simulado no iniciado"));}
 @Override public PaymentTerminalResult charge(PaymentTerminalChargeCommand c,PaymentTerminalGatewayContext x){validate(x);return operations.computeIfAbsent(c.operationId(),ignored->configured(x,c.operationId(),true,"simulatorOutcome"));}
 @Override public PaymentTerminalResult query(PaymentTerminalQueryCommand c,PaymentTerminalGatewayContext x){validate(x);var stored=operations.get(c.operationId());if(stored==null)return result(PaymentTerminalOperationStatus.ERROR,"OPERATION_NOT_FOUND",id(c.operationId()),null,"Operacion simulada no encontrada");if(stored.status()!=PaymentTerminalOperationStatus.PENDING&&stored.status()!=PaymentTerminalOperationStatus.TIMEOUT)return stored;if(x.parameters().get("simulatorQueryOutcome")==null)return stored;var resolved=configured(x,c.operationId(),true,"simulatorQueryOutcome");operations.put(c.operationId(),resolved);return resolved;}
 @Override public PaymentTerminalResult voidAuthorization(PaymentTerminalVoidCommand c,PaymentTerminalGatewayContext x){validate(x);return result(PaymentTerminalOperationStatus.CANCELLED,"VOIDED",id(c.operationId()),null,"Autorizacion simulada anulada");}
 @Override public PaymentTerminalResult refund(PaymentTerminalRefundCommand c,PaymentTerminalGatewayContext x){validate(x);return result(PaymentTerminalOperationStatus.PARTIALLY_REFUNDED,"PARTIAL_REFUND",id(c.operationId()),id(c.operationId()).substring(0,8),"Devolucion parcial simulada aprobada");}
 @Override public PaymentTerminalReceipt receipt(PaymentTerminalReceiptCommand c,PaymentTerminalGatewayContext x){validate(x);return new PaymentTerminalReceipt(provider.name()+"\nREFERENCIA "+safe(c.reference())+"\nOPERACION "+c.operationId());}
 @Override public PaymentTerminalResult reconcile(PaymentTerminalReconciliationCommand c,PaymentTerminalGatewayContext x){validate(x);return result(PaymentTerminalOperationStatus.APPROVED,"RECONCILED",id(c.reconciliationId()),null,"Conciliacion simulada completada");}
 @Override public CardTerminalResult testConnection(CardTerminalConfiguration c){var d=legacyDiagnostic(c);if(d!=null)return legacyError(d);return legacy(outcome(c.parameters().get("simulatorOutcome")),UUID.randomUUID());}
 @Override public CardTerminalResult charge(CardTerminalRequest r,CardTerminalConfiguration c){var d=legacyDiagnostic(c);if(d!=null)return legacyError(d);if(r.provider()!=provider)return legacyError("Proveedor de la solicitud no compatible");if(!r.terminalId().equals(c.terminalId()))return legacyError("La solicitud no corresponde al terminal configurado");return legacy(outcome(c.parameters().get("simulatorOutcome")),r.checkoutId());}
 private void validate(PaymentTerminalGatewayContext x){if(x.provider()!=provider)throw new IllegalArgumentException("provider mismatch");if(x.mode()!=PaymentTerminalMode.SIMULATED)throw new IllegalArgumentException("simulated mode required");}
 private PaymentTerminalResult configured(PaymentTerminalGatewayContext x,UUID id,boolean authorization,String parameter){var status=outcome(x.parameters().get(parameter));return result(status,code(status),id(id),status==PaymentTerminalOperationStatus.APPROVED&&authorization?id(id).substring(0,8):null,message(status));}
 private PaymentTerminalOperationStatus outcome(String value){if(value==null)return PaymentTerminalOperationStatus.ERROR;try{return PaymentTerminalOperationStatus.valueOf(value.trim().toUpperCase(Locale.ROOT).replace("CONNECTION_ERROR","ERROR"));}catch(IllegalArgumentException e){return PaymentTerminalOperationStatus.ERROR;}}
 private String legacyDiagnostic(CardTerminalConfiguration c){if(!c.enabled())return "Configuracion de datafono desactivada";if(c.mode()!=PaymentCardMode.INTEGRATED)return "El datafono requiere modo integrado";if(c.provider()!=provider)return "Proveedor incompatible";if(!c.testMode())return "SDK no disponible";return null;}
 private CardTerminalResult legacy(PaymentTerminalOperationStatus s,UUID operation){var id=id(operation);return new CardTerminalResult(s,"SIM-"+id,s==PaymentTerminalOperationStatus.APPROVED?"SIMAUTH-"+id.substring(0,8):null,message(s));}
 private CardTerminalResult legacyError(String m){return new CardTerminalResult(PaymentTerminalOperationStatus.ERROR,null,null,m);}
 private PaymentTerminalResult result(PaymentTerminalOperationStatus s,String code,String ref,String auth,String m){return new PaymentTerminalResult(s,code,provider.name()+"-SIM-"+ref,auth==null?null:provider.name()+"-SIMAUTH-"+auth,m);}
 private String id(UUID id){return id.toString().replace("-","").toUpperCase(Locale.ROOT);}private String code(PaymentTerminalOperationStatus s){return s==PaymentTerminalOperationStatus.ERROR?"SIMULATOR_ERROR":s.name();}
 private String message(PaymentTerminalOperationStatus s){return "Operacion simulada "+s.name().toLowerCase(Locale.ROOT);}private String safe(String v){var cleaned=v.replaceAll("[^A-Za-z0-9._-]","");return cleaned.substring(0,Math.min(64,cleaned.length()));}
}
