package com.tpverp.saas.admin;

public enum AdminPermission {
    ADD_COMPANY,
    RENEW_LICENSE,
    BLOCK_LICENSE,
    UNBLOCK_LICENSE,
    EDIT_COMPANY_DATA,
    VIEW_ADMIN_DATA,
    REGENERATE_PAIRING_CODE,
    MANAGE_ADMIN_USERS,
    MANAGE_SUPPORT_TICKETS,
    MANAGE_BILLING,
    MANAGE_TENANT_USERS,
    MANAGE_ERP_MASTERS,
    MANAGE_FISCAL_POLICY,
    MANAGE_OPERATIONS,
    MANAGE_SUBSCRIPTIONS,
    MANAGE_INTEGRATIONS,
    VIEW_REPORTS
}
