package com.tpverp.backend.document;
import static org.assertj.core.api.Assertions.assertThat;
import java.util.UUID;
import jakarta.validation.Validation;
import org.junit.jupiter.api.Test;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;
class SalePaymentSessionControllerContractTest {
 @Test void exposesValidatedSimulatorDiscardContract() throws Exception {var method=SalePaymentSessionController.class.getDeclaredMethod("discardSimulation",UUID.class,SalePaymentSessionController.SimulatorDiscard.class,Authentication.class);assertThat(method.getAnnotation(PostMapping.class).value()).containsExactly("/{id}/simulator-discard");var validator=Validation.buildDefaultValidatorFactory().getValidator();assertThat(validator.validate(new SalePaymentSessionController.SimulatorDiscard("application_shutdown"))).isEmpty();assertThat(validator.validate(new SalePaymentSessionController.SimulatorDiscard("sale_entry_cleanup"))).isEmpty();assertThat(validator.validate(new SalePaymentSessionController.SimulatorDiscard(""))).isNotEmpty();assertThat(validator.validate(new SalePaymentSessionController.SimulatorDiscard("logout"))).isNotEmpty();}
 @Test void exposesReloadAllocationQueryFinalizeAndCancelBehindSalePermission() throws Exception {assertThat(SalePaymentSessionController.class.getAnnotation(RequestMapping.class).value()).containsExactly("/api/v1/pos/payment-sessions");assertThat(SalePaymentSessionController.class.getAnnotation(PreAuthorize.class).value()).contains("TICKETS_CREATE");assertThat(SalePaymentSessionController.class.getDeclaredMethod("get",UUID.class,Authentication.class).getAnnotation(GetMapping.class).value()).containsExactly("/{id}");assertThat(SalePaymentSessionController.class.getDeclaredMethod("add",UUID.class,SalePaymentSessionController.Allocation.class,Authentication.class).getAnnotation(PostMapping.class).value()).containsExactly("/{id}/allocations");assertThat(SalePaymentSessionController.class.getDeclaredMethod("query",UUID.class,UUID.class,Authentication.class).getAnnotation(PostMapping.class).value()).containsExactly("/{id}/allocations/{allocationId}/query");assertThat(SalePaymentSessionController.class.getDeclaredMethod("finalizeSession",UUID.class,Authentication.class).getAnnotation(PostMapping.class).value()).containsExactly("/{id}/finalize");}
 @Test void mutationsUseAPessimisticSessionLock() throws Exception {var lock=SalePaymentSessionRepository.class.getDeclaredMethod("findLocked",UUID.class).getAnnotation(org.springframework.data.jpa.repository.Lock.class);assertThat(lock.value()).isEqualTo(jakarta.persistence.LockModeType.PESSIMISTIC_WRITE);}
 @Test void activeRecoveryIsServerScopedByStoreTerminalAndUser() throws Exception {assertThat(SalePaymentSessionController.class.getDeclaredMethod("active",Authentication.class).getAnnotation(GetMapping.class).value()).containsExactly("/active");var query=SalePaymentSessionRepository.class.getDeclaredMethod("findActive",UUID.class,UUID.class,UUID.class).getAnnotation(org.springframework.data.jpa.repository.Query.class).value();assertThat(query).contains("s.storeId=:storeId","s.terminalId=:terminalId","s.userId=:userId");}
}
