package com.tpverp.backend.document;
import static org.mockito.Mockito.*;
import static org.assertj.core.api.Assertions.*;
import com.tpverp.backend.organization.*;
import com.tpverp.backend.terminal.*;
import java.math.BigDecimal;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.springframework.security.core.Authentication;
import com.tpverp.backend.security.domain.UserAccount;

class SalePaymentSessionServiceTest {
 @Test void repeatedIntegratedAllocationKeyChargesGatewayOnceAndReloadKeepsApproval(){
  var repo=mock(SalePaymentSessionRepository.class);var sales=mock(PosCashService.class);var docs=mock(DocumentService.class);var snapshots=mock(PosCardDocumentSnapshot.class);var methods=mock(PaymentMethodRepository.class);var org=mock(CurrentOrganization.class);var terminal=mock(CurrentTerminal.class);var configs=mock(CardTerminalConfigurationReader.class);var ops=mock(PaymentTerminalOperationService.class);var auth=mock(Authentication.class);
  var storeId=UUID.randomUUID();var terminalId=UUID.randomUUID();var userId=UUID.randomUUID();var sessionId=UUID.randomUUID();var allocationId=UUID.randomUUID();var store=mock(Store.class);var user=mock(UserAccount.class);when(user.getId()).thenReturn(userId);when(auth.getPrincipal()).thenReturn(user);when(store.getId()).thenReturn(storeId);when(org.currentStore()).thenReturn(store);when(terminal.terminalId(auth)).thenReturn(terminalId);
  var session=SalePaymentSession.reserve(sessionId,storeId,terminalId,userId,"hash","{}",new BigDecimal("10.00"));when(repo.findLocked(sessionId)).thenReturn(Optional.of(session));when(repo.findState(sessionId)).thenReturn(Optional.of(session));when(repo.save(any())).thenAnswer(i->i.getArgument(0));var config=new CardTerminalConfiguration(terminalId,storeId,PaymentCardMode.INTEGRATED,PaymentTerminalProvider.PAYTEF,true,true,"PAYTEF","ref",1,"cfg",Map.of());when(configs.required(terminalId)).thenReturn(config);when(ops.charge(eq(allocationId),anyString(),eq(new BigDecimal("10.00")),eq(config))).thenAnswer(invocation->{assertThat(invocation.getArgument(1,String.class)).matches("[a-f0-9]{64}");assertThat(session.getAllocations()).singleElement().satisfies(a->assertThat(a.getOperationId()).isNull());return new PaymentTerminalResult(PaymentTerminalOperationStatus.APPROVED,"OK","ref","auth","Aprobado");});
  var service=new SalePaymentSessionService(repo,sales,docs,snapshots,methods,org,terminal,configs,ops);
  service.add(sessionId,allocationId,"stable",SalePaymentAllocationKind.INTEGRATED_CARD,new BigDecimal("10.00"),"PAYTEF",null,auth);
  service.add(sessionId,UUID.randomUUID(),"stable",SalePaymentAllocationKind.INTEGRATED_CARD,new BigDecimal("10.00"),"PAYTEF",null,auth);
  verify(ops,times(1)).charge(eq(allocationId),anyString(),eq(new BigDecimal("10.00")),eq(config));assertThat(session.getAllocations()).singleElement().satisfies(a->assertThat(a.getStatus()).isEqualTo(PaymentTerminalOperationStatus.APPROVED));session.cancel();var unresolved=mock(PaymentTerminalOperation.class);when(unresolved.getStatus()).thenReturn(PaymentTerminalOperationStatus.APPROVED);when(ops.find(allocationId)).thenReturn(Optional.of(unresolved));assertThatThrownBy(()->service.acknowledgeCompensation(sessionId,"resuelto",auth)).hasMessage("integrated_compensation_unresolved");
  var other=mock(UserAccount.class);when(other.getId()).thenReturn(UUID.randomUUID());when(auth.getPrincipal()).thenReturn(other);assertThatThrownBy(()->service.get(sessionId,auth)).isInstanceOf(NoSuchElementException.class);
 }
 @Test void failureAfterPendingCommitKeepsStableAllocationAndRetryDoesNotCreateAnother(){
  var repo=mock(SalePaymentSessionRepository.class);var sales=mock(PosCashService.class);var docs=mock(DocumentService.class);var snapshots=mock(PosCardDocumentSnapshot.class);var methods=mock(PaymentMethodRepository.class);var org=mock(CurrentOrganization.class);var terminal=mock(CurrentTerminal.class);var configs=mock(CardTerminalConfigurationReader.class);var ops=mock(PaymentTerminalOperationService.class);var auth=mock(Authentication.class);
  var storeId=UUID.randomUUID();var terminalId=UUID.randomUUID();var userId=UUID.randomUUID();var sessionId=UUID.randomUUID();var allocationId=UUID.randomUUID();var store=mock(Store.class);var user=mock(UserAccount.class);when(user.getId()).thenReturn(userId);when(auth.getPrincipal()).thenReturn(user);when(store.getId()).thenReturn(storeId);when(org.currentStore()).thenReturn(store);when(terminal.terminalId(auth)).thenReturn(terminalId);var session=SalePaymentSession.reserve(sessionId,storeId,terminalId,userId,"hash","{}",new BigDecimal("10.00"));when(repo.findLocked(sessionId)).thenReturn(Optional.of(session));when(repo.save(any())).thenAnswer(i->i.getArgument(0));var config=new CardTerminalConfiguration(terminalId,storeId,PaymentCardMode.INTEGRATED,PaymentTerminalProvider.PAYTEF,true,true,"PAYTEF","ref",1,"cfg",Map.of());when(configs.required(terminalId)).thenThrow(new IllegalStateException("offline")).thenReturn(config);when(ops.charge(eq(allocationId),anyString(),eq(new BigDecimal("10.00")),eq(config))).thenReturn(new PaymentTerminalResult(PaymentTerminalOperationStatus.APPROVED,"OK","ref","auth","Aprobado"));var service=new SalePaymentSessionService(repo,sales,docs,snapshots,methods,org,terminal,configs,ops);
  when(repo.findState(sessionId)).thenReturn(Optional.of(session));assertThatThrownBy(()->service.add(sessionId,UUID.randomUUID(),"manual",SalePaymentAllocationKind.MANUAL_CARD,new BigDecimal("1.00"),null," ",auth)).hasMessage("manual_card_reference_required");assertThat(session.getAllocations()).isEmpty();assertThatThrownBy(()->service.add(sessionId,allocationId,"stable",SalePaymentAllocationKind.INTEGRATED_CARD,new BigDecimal("10.00"),"PAYTEF",null,auth)).hasMessage("offline");assertThat(session.getAllocations()).isEmpty();service.add(sessionId,allocationId,"stable",SalePaymentAllocationKind.INTEGRATED_CARD,new BigDecimal("10.00"),"PAYTEF",null,auth);assertThat(session.getAllocations()).singleElement().satisfies(a->{assertThat(a.getId()).isEqualTo(allocationId);assertThat(a.getOperationId()).isEqualTo(allocationId);});verify(ops,times(1)).charge(eq(allocationId),anyString(),any(),eq(config));
 }
 @Test void finalizeRejectsAnIntegratedAllocationWhoseChargeWasAdjusted(){
  var repo=mock(SalePaymentSessionRepository.class);var sales=mock(PosCashService.class);var docs=mock(DocumentService.class);var snapshots=mock(PosCardDocumentSnapshot.class);var methods=mock(PaymentMethodRepository.class);var org=mock(CurrentOrganization.class);var terminal=mock(CurrentTerminal.class);var configs=mock(CardTerminalConfigurationReader.class);var ops=mock(PaymentTerminalOperationService.class);var auth=mock(Authentication.class);
  var storeId=UUID.randomUUID();var terminalId=UUID.randomUUID();var userId=UUID.randomUUID();var sessionId=UUID.randomUUID();var allocationId=UUID.randomUUID();var store=mock(Store.class);var user=mock(UserAccount.class);when(user.getId()).thenReturn(userId);when(auth.getPrincipal()).thenReturn(user);when(store.getId()).thenReturn(storeId);when(org.currentStore()).thenReturn(store);when(terminal.terminalId(auth)).thenReturn(terminalId);
  var session=SalePaymentSession.reserve(sessionId,storeId,terminalId,userId,"hash","{}",new BigDecimal("10.00"));session.addAllocation(allocationId,"card",SalePaymentAllocationKind.INTEGRATED_CARD,new BigDecimal("10.00"),"PAYTEF","INTEGRATED").approve(allocationId,"ref","auth");when(repo.findLocked(sessionId)).thenReturn(Optional.of(session));doThrow(new IllegalStateException("payment_operation_not_finalizable")).when(ops).requireFinalizableApprovedCharge(allocationId);
  var service=new SalePaymentSessionService(repo,sales,docs,snapshots,methods,org,terminal,configs,ops);
  assertThatThrownBy(()->service.finalizeSession(sessionId,auth)).hasMessage("payment_operation_not_finalizable");
  verify(docs,never()).createApprovedCardTicketFromSnapshot(any(),any(),eq(auth));
 }
}
