package com.tpverp.backend.document;
import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assumptions.assumeTrue;
import java.sql.*;import java.util.UUID;import java.util.concurrent.*;import org.flywaydb.core.Flyway;import org.junit.jupiter.api.Test;
class SalePaymentFinalizeConcurrencyPostgreSqlTest {
 @Test void simultaneousFinalizeLockCreatesExactlyOneTicket() throws Exception {
  var url=env("TPV_ERP_TEST_DB_URL","TPV_TEST_DB_URL");var user=env("TPV_ERP_TEST_DB_USER","TPV_TEST_DB_USERNAME");var password=env("TPV_ERP_TEST_DB_PASSWORD","TPV_TEST_DB_PASSWORD");assumeTrue(url!=null&&!url.isBlank());
  var schema="payment_finalize_"+UUID.randomUUID().toString().replace("-","");var company=UUID.randomUUID();var store=UUID.randomUUID();var terminal=UUID.randomUUID();var role=UUID.randomUUID();var operator=UUID.randomUUID();var warehouse=UUID.randomUUID();var session=UUID.randomUUID();
  try { Flyway.configure().dataSource(url,user,password).schemas(schema).defaultSchema(schema).createSchemas(true).load().migrate();
   try(var c=DriverManager.getConnection(url,user,password);var s=c.createStatement()){s.execute("set search_path to "+schema);s.executeUpdate("insert into empresa(id,tax_id,razon_social,domicilio_fiscal) values ('"+company+"','B1','Test','{\"linea1\":\"x\",\"ciudad\":\"x\",\"codigoPostal\":\"1\",\"provincia\":\"x\",\"pais\":\"ES\"}')");s.executeUpdate("insert into tienda(id,empresa_id,nombre,direccion,address_normalized_hash,timezone,moneda,locale,codigo_tienda) values ('"+store+"','"+company+"','T','{\"linea1\":\"x\",\"ciudad\":\"x\",\"codigoPostal\":\"1\",\"provincia\":\"x\",\"pais\":\"ES\"}','h','Europe/Madrid','EUR','es-ES','001')");s.executeUpdate("insert into terminal(id,tienda_id,nombre,tipo,credential_hash) values ('"+terminal+"','"+store+"','TPV','TERMINAL_VENTA','h')");s.executeUpdate("insert into rol(id,tienda_id,nombre) values ('"+role+"','"+store+"','SELLER')");s.executeUpdate("insert into usuario(id,tienda_id,nombre,user_name,password_hash,rol_id) values ('"+operator+"','"+store+"','SELLER','Seller','h','"+role+"')");s.executeUpdate("insert into almacen(id,tienda_id,nombre,predeterminado) values ('"+warehouse+"','"+store+"','A',true)");s.executeUpdate("insert into sale_payment_session(id,store_id,terminal_id,user_id,request_hash,document_snapshot,total,currency,status,created_at,updated_at) values ('"+session+"','"+store+"','"+terminal+"','"+operator+"','h','{}',1,'EUR','COVERED',now(),now())");}
   var start=new CountDownLatch(1);var pool=Executors.newFixedThreadPool(2);Callable<Integer> finalize=()->{start.await();try(var c=DriverManager.getConnection(url,user,password)){c.setAutoCommit(false);try(var s=c.createStatement()){s.execute("set search_path to "+schema);UUID existing=null;try(var r=s.executeQuery("select ticket_id from sale_payment_session where id='"+session+"' for update")){r.next();existing=(UUID)r.getObject(1);}if(existing!=null){c.commit();return 0;}var ticket=UUID.randomUUID();s.executeUpdate("insert into documento(id,tienda_id,almacen_id,tipo,estado,numero,fecha,creado_en,creado_por,total) values ('"+ticket+"','"+store+"','"+warehouse+"','TICKET','CONFIRMADO','T-1',current_date,now(),'"+operator+"',1)");s.executeUpdate("update sale_payment_session set ticket_id='"+ticket+"',ticket_number='T-1',status='FINALIZED' where id='"+session+"'");c.commit();return 1;}}};var a=pool.submit(finalize);var b=pool.submit(finalize);start.countDown();assertThat(a.get(15,TimeUnit.SECONDS)+b.get(15,TimeUnit.SECONDS)).isEqualTo(1);try(var c=DriverManager.getConnection(url,user,password);var s=c.createStatement();var r=s.executeQuery("select count(*) from "+schema+".documento where numero='T-1'")){r.next();assertThat(r.getInt(1)).isEqualTo(1);}pool.shutdownNow();
  } finally {try(var c=DriverManager.getConnection(url,user,password);var s=c.createStatement()){s.execute("drop schema if exists "+schema+" cascade");}}
 }
 private static String env(String first,String second){var value=System.getenv(first);return value==null||value.isBlank()?System.getenv(second):value;}
}
