package com.tpverp.backend.party;

public enum MemberMovementType {
    ALTA_MIEMBRO,
    DESACTIVACION_MIEMBRO,
    CAMBIO_CATEGORIA,
    ACUMULACION_PUNTOS,
    ACUMULACION_SALDO,
    USO_SALDO,
    CADUCIDAD_SALDO,
    AJUSTE_MANUAL_SALDO,
    AJUSTE_MANUAL_PUNTOS,
    AJUSTE_SAAS,
    ANULACION_ACUMULACION_PUNTOS,
    ANULACION_ACUMULACION_SALDO,
    ANULACION_USO_SALDO,
    DEVOLUCION_ACUMULACION_PUNTOS,
    DEVOLUCION_ACUMULACION_SALDO,
    DEVOLUCION_RESTAURACION_SALDO,
    PAGO_DEUDA_PUNTOS,
    PAGO_DEUDA_SALDO,
    ABONO_CREDITO_DEVOLUCION,
    USO_CREDITO_DEVOLUCION,
    CADUCIDAD_CREDITO_DEVOLUCION
}
