import { useI18n } from "../../i18n";
const labels = {
  title: ["Asistencia remota y presencial", "Remote and on-site assistance", "远程与现场协助"],
  phase: ["Fase de intervención", "Intervention stage", "处理阶段"],
  note: ["Nota de la intervención (obligatoria)", "Intervention note (required)", "处理备注（必填）"],
  noteRequired: ["Escribe una nota de entre 5 y 2000 caracteres.", "Enter a note of 5 to 2000 characters.", "请输入 5 至 2000 个字符的处理备注。"],
  remoteId: ["ID de TeamViewer (opcional)", "TeamViewer ID (optional)", "TeamViewer ID（可选）"],
  emptyRemoteId: ["Dejar el ID vacío al iniciar una nueva asistencia elimina el ID anterior; no se reutiliza.", "Starting new assistance with an empty ID clears the previous ID; it is not reused.", "开始新协助时留空将清除之前的 ID，不会自动沿用。"],
  invalidId: ["El ID de TeamViewer debe contener entre 6 y 15 dígitos.", "TeamViewer ID must contain 6 to 15 digits.", "TeamViewer ID 必须为 6 至 15 位数字。"],
  copy: ["Copiar ID de TeamViewer", "Copy TeamViewer ID", "复制 TeamViewer ID"],
  copied: ["ID de TeamViewer copiado.", "TeamViewer ID copied.", "已复制 TeamViewer ID。"],
  copyFailed: ["No se pudo copiar. Selecciona el ID y cópialo manualmente.", "Could not copy. Select and copy the ID manually.", "复制失败，请选中 ID 手动复制。"],
  open: ["Abrir TeamViewer oficial", "Open official TeamViewer", "打开 TeamViewer 官网"],
  external: ["La conexión se realiza fuera de SaaS. Abrir TeamViewer no significa que se haya conectado con el cliente.", "The connection happens outside SaaS. Opening TeamViewer does not mean a connection to the customer has been established.", "连接在 SaaS 外部完成，打开 TeamViewer 不代表已连接客户设备。"],
  loading: ["Consultando intervención…", "Loading intervention…", "正在查询处理流程…"],
  reload: ["Actualizar intervención", "Refresh intervention", "刷新处理流程"],
  readError: ["No se pudo consultar la intervención. Actualiza antes de operar.", "Could not load intervention state. Refresh before taking action.", "无法获取处理状态，请刷新后再操作。"],
  writeError: ["No se pudo confirmar la solicitud. Reintenta la misma solicitud o actualiza para comprobarla.", "The request could not be confirmed. Retry the same request or refresh to check it.", "请求结果尚未确认，请重试同一请求或刷新核对。"],
  conflict: ["La intervención o el ticket ha cambiado. Actualiza y revisa la fase antes de volver a solicitar la acción.", "The intervention or ticket changed. Refresh and review the stage before requesting the action again.", "处理流程或工单状态已变化，请刷新并核对当前阶段后重新操作。"],
  rejected: ["El servidor rechazó la solicitud. Actualiza el estado antes de intentarlo de nuevo.", "The server rejected the request. Refresh the state before trying again.", "服务器拒绝了请求，请刷新状态后再试。"],
  pending: ["Hay una solicitud sin confirmar; se conservarán su identificador, nota y versión al reintentar.", "A request is unconfirmed; retries preserve its identifier, note and version.", "有待确认请求，重试将保留原标识、备注和版本。"],
  retry: ["Reintentar intervención pendiente", "Retry pending intervention", "重试待确认处理操作"],
  saved: ["Intervención registrada.", "Intervention recorded.", "处理记录已保存。"],
  permission: ["No tienes permiso para registrar intervenciones.", "You do not have permission to record interventions.", "你没有记录处理操作的权限。"],
  history: ["Historial de intervenciones", "Intervention history", "处理历史"],
  noHistory: ["Aún no hay intervenciones registradas.", "No interventions recorded yet.", "暂无处理记录。"],
  actor: ["Responsable", "Operator", "操作人"],
  time: ["Fecha", "Time", "时间"],
  unknown: ["Estado no reconocido; actualiza o consulta con un administrador.", "Unrecognized state; refresh or contact an administrator.", "未识别的状态，请刷新或联系管理员。"],
  REMOTE_PENDING: ["Pendiente de asistencia remota", "Remote assistance pending", "等待远程协助"],
  REMOTE_IN_PROGRESS: ["Asistencia remota en curso", "Remote assistance in progress", "远程协助中"],
  ONSITE_REQUIRED: ["Requiere visita presencial", "On-site visit required", "需要现场处理"],
  ONSITE_IN_PROGRESS: ["Visita presencial en curso", "On-site visit in progress", "现场处理中"],
  RESOLVED: ["Intervención resuelta", "Intervention resolved", "处理已完成"],
  START_REMOTE: ["Iniciar asistencia remota", "Start remote assistance", "开始远程协助"],
  REQUIRE_ONSITE: ["Derivar a visita presencial", "Require on-site visit", "转现场处理"],
  START_ONSITE: ["Iniciar visita presencial", "Start on-site visit", "开始现场处理"],
  RESOLVE: ["Resolver intervención", "Resolve intervention", "完成处理"],
  REOPEN: ["Reabrir intervención", "Reopen intervention", "重新打开处理流程"],
} as const;
export function useInterventionLabels() {
  const { language } = useI18n();
  return (key: string) => (labels[key as keyof typeof labels] ?? labels.unknown)[language === "es" ? 0 : language === "en" ? 1 : 2];
}
