import { useI18n } from "../../i18n";
const labels = {
  START_SAAS: ["Trabajar desde SaaS","Work from SaaS","在 SaaS 中处理"],
  SAAS_IN_PROGRESS: ["Diagnóstico y actuación desde SaaS","Diagnosis and work from SaaS","SaaS 诊断处理中"],
  SAAS_IN_PROGRESS_HELP: ["Comprueba la configuración o realiza el ajuste necesario. Registra la solución antes de comprobar el resultado.","Check configuration or apply the necessary change. Record the solution before verifying the outcome.","检查配置或执行调整，验证结果前记录解决方法。"],
  WAIT_CUSTOMER: ["Esperar al cliente","Wait for customer","等待客户"],
  WAIT_MATERIAL: ["Esperar material","Wait for material","等待材料"],
  WAITING_CUSTOMER: ["Esperando al cliente","Waiting for customer","等待客户"],
  WAITING_MATERIAL: ["Esperando material","Waiting for material","等待材料"],
  WAITING_CUSTOMER_HELP: ["Revisa la fecha de seguimiento y retoma la fase anterior cuando el cliente responda.","Check the follow-up date and resume the previous phase when the customer responds.","客户回复后恢复之前的阶段，请关注跟进日期。"],
  WAITING_MATERIAL_HELP: ["Revisa la fecha de seguimiento y retoma el trabajo cuando llegue el material.","Check the follow-up date and resume work when the material arrives.","材料到达后恢复处理，请关注跟进日期。"],
  RESUME: ["Retomar trabajo","Resume work","继续处理"],
  nextReviewAt: ["Próxima revisión (para dejar en espera)","Next review (when waiting)","下次跟进（等待时必填）"],
  reviewRequired: ["Indica una fecha futura para revisar la espera y explica el motivo en la nota.","Enter a future follow-up date and explain the waiting reason in the note.","请输入未来的跟进时间，并在备注中说明等待原因。"],
  resumePhase: ["Al retomar volverás a","Resuming returns to","继续后返回"],
  unassigned: ["Sin asignar","Unassigned","未分配"],
  legacyAssignee: ["Responsable anterior sin usuario vinculado","Previous owner without a linked user","此前负责人未关联用户"],
  closedPending: ["Atención cerrada · recuperación técnica pendiente","Support closed · technical recovery pending","处理已关闭 · 等待技术恢复确认"],
  latestReceipt: ["Última información recibida","Latest information received","最新接收信息"],
  privateNote: ["Nota interna de intervención (obligatoria)","Internal intervention note (required)","内部处理备注（必填）"],
  notePrivacy: ["Se guarda en el historial interno. Para comunicarte con el cliente, utiliza un comentario del ticket.","Saved in internal history. Use a ticket comment to communicate with the customer.","保存到内部历史。与客户沟通请使用工单评论。"],
  timeline: ["Cronología de la incidencia","Incident timeline","事件时间线"],
  timelineEmpty: ["Todavía no hay actividad registrada.","No activity recorded yet.","暂无记录。"],
  timelineError: ["No se pudo cargar toda la cronología. Actualiza para volver a consultar los comentarios y los intentos.","The complete timeline could not be loaded. Refresh to retrieve comments and attempts again.","无法加载完整时间线，请刷新重试。"],
  internal: ["Intervención interna","Internal intervention","内部处理"],
  customerComment: ["Comentario del ticket · visible para el cliente","Ticket comment · visible to the customer","工单评论 · 客户可见"],
  automatic: ["Intento automático","Automatic attempt","自动尝试"],
  waitReason: ["Motivo de la espera","Waiting reason","等待原因"],
  reviewDate: ["Revisar el","Review on","跟进时间"],
  historyTime: ["Fecha de la actividad","Activity time","记录时间"],
  scope: ["El ticket registra la atención. La confirmación del fallo técnico se muestra por separado.","The ticket records support work. Technical recovery is shown separately.","工单记录协助工作，技术恢复状态单独显示。"],
  closePanel: ["Cerrar seguimiento","Close follow-up","关闭跟进"],
  manage: ["Gestionar incidencia","Manage incident","管理事件"],
  legacyClosure: ["Cierre anterior sin comprobación estructurada. Puedes reabrir el caso si requiere revisión.","Earlier closure without structured verification. Reopen if review is needed.","旧工单关闭时无结构化验证，可在需要时重新打开。"],
  technicalRecovered: ["La tienda ha comunicado la recuperación del fallo.","The store reported recovery of the failure.","门店已报告故障恢复。"],
  technicalPending: ["La recuperación del dispositivo aún no está confirmada. El cierre del ticket no cambia este estado.","Device recovery is not yet confirmed. Closing the ticket does not change this state.","设备恢复尚未确认，关闭工单不会改变此状态。"],
  noLinkedFailure: ["Ticket general: sin fallo técnico vinculado.","General ticket: no linked technical failure.","普通工单：未关联技术故障。"],
  linkedFailure: ["Fallo técnico vinculado","Linked technical failure","关联技术故障"],
  visitRequired: ["Guarda la fecha de visita antes de iniciarla.","Save the visit date before starting.","开始前请保存上门日期。"],
  planningRequired: ["Indica un responsable y una fecha válida si programas una visita.","Enter an owner and a valid date if scheduling a visit.","请填写负责人，以及有效的上门日期（如安排）。"],
  evidenceRequired: ["Completa la solución o las comprobaciones y la persona que confirma para continuar.","Complete the solution or checks and confirming person before continuing.","继续前请填写解决方法或检查结果及确认人。"],
  confirmedBy: ["Confirmado por (cliente o técnico)","Confirmed by (customer or technician)","确认人（客户或技术人员）"],
  verificationNotes: ["Comprobaciones realizadas","Checks performed","已执行的检查"],
  resolutionSummary: ["Solución aplicada","Solution applied","解决方法"],
  AWAITING_VERIFICATION_HELP: ["Comprueba el funcionamiento. Registra las pruebas y quién lo confirma antes de cerrar. Si continúa fallando, vuelve a diagnóstico o deriva a una visita.","Check operation. Record tests and who confirms before closing. If it still fails, return to diagnosis or refer for a visit.","检查运行情况，关闭前记录测试及确认人。如仍有故障，可返回诊断或转现场处理。"],
  AWAITING_VERIFICATION: ["Pendiente de comprobación","Awaiting verification","等待验证"],
  VERIFICATION_FAILED: ["No funciona: volver a diagnóstico","Not working: return to diagnosis","未恢复：返回诊断"],
  REQUEST_VERIFICATION: ["Pasar a comprobación","Request verification","进入验证"],
  SAVE_DETAILS: ["Guardar planificación","Save schedule","保存计划"],
  visitHelp: ["Hora local del navegador. Guarda la planificación antes de iniciar la visita.","Browser local time. Save the schedule before starting the visit.","使用浏览器当地时间，请先保存计划再开始现场处理。"],
  visitAt: ["Fecha y hora de visita","Visit date and time","上门日期和时间"],
  assignee: ["Responsable asignado","Assigned owner","指定负责人"],
  planning: ["Responsable y planificación","Owner and scheduling","负责人和计划"],
  remoteTools: ["Conexión con el cliente","Customer connection","连接客户"],
  nextStep: ["Siguiente paso","Next step","下一步"],
  notePlaceholder: ["Describe la actuación o el resultado antes de continuar.","Describe the action or outcome before continuing.","继续前请描述处理操作或结果。"],
  REMOTE_PENDING_HELP: ["Empieza por el diagnóstico desde SaaS. Si necesitas acceder al equipo, inicia asistencia remota o coordina una visita.","Start with diagnosis from SaaS. Use remote assistance or arrange a visit if device access is needed.","先在 SaaS 中诊断，如需访问设备，可开始远程协助或安排现场处理。"],
  REMOTE_IN_PROGRESS_HELP: ["Describe la solución aplicada y pasa a comprobación. Si necesitas atender el equipo presencialmente, deriva a una visita.","Describe the solution and request verification, or refer for an on-site visit.","描述解决方法并进入验证，或转现场处理。"],
  ONSITE_REQUIRED_HELP: ["Coordina la visita con el cliente y registra su inicio cuando el técnico empiece a trabajar.","Arrange the visit with the customer and record its start when the technician begins work.","与客户安排上门时间，在技术人员开始工作时记录。"],
  ONSITE_IN_PROGRESS_HELP: ["Registra la solución aplicada durante la visita y pasa a comprobación.","Record the solution applied during the visit and request verification.","记录现场解决方法并进入验证。"],
  RESOLVED_HELP: ["La atención está cerrada. Si el problema continúa, escribe el motivo y reabre la intervención.","Support is closed. If the problem persists, enter the reason and reopen the intervention.","处理已关闭。如果问题仍然存在，请填写原因并重新打开。"],
  title: ["Seguimiento de la incidencia","Incident follow-up","事件跟进"],
  phase: ["Fase de intervención", "Intervention stage", "处理阶段"],
  note: ["Nota de la intervención (obligatoria)", "Intervention note (required)", "处理备注（必填）"],
  noteRequired: ["Escribe una nota de entre 5 y 2000 caracteres.", "Enter a note of 5 to 2000 characters.", "请输入 5 至 2000 个字符的处理备注。"],
  remoteId: ["ID de TeamViewer (opcional)", "TeamViewer ID (optional)", "TeamViewer ID（可选）"],
  emptyRemoteId: ["Dejar el ID vacío al iniciar una nueva asistencia elimina el ID anterior; no se reutiliza.", "Starting new assistance with an empty ID clears the previous ID; it is not reused.", "开始新协助时留空将清除之前的 ID，不会自动沿用。"],
  invalidId: ["El ID de TeamViewer debe contener entre 6 y 15 dígitos.", "TeamViewer ID must contain 6 to 15 digits.", "TeamViewer ID 必须为 6 至 15 位数字。"],
  copy: ["Copiar ID de TeamViewer", "Copy TeamViewer ID", "复制 TeamViewer ID"],
  copied: ["ID de TeamViewer copiado.", "TeamViewer ID copied.", "已复制 TeamViewer ID。"],
  copyFailed: ["No se pudo copiar. Selecciona el ID y cópialo manualmente.", "Could not copy. Select and copy the ID manually.", "复制失败，请选中 ID 手动复制。"],
  open: ["Abrir TeamViewer oficial", "Open official TeamViewer", "打开 TeamViewer 官网"],
  external: ["La conexión se realiza fuera de SaaS. Abrir TeamViewer no significa que se haya conectado con el cliente.", "The connection happens outside SaaS. Opening TeamViewer does not mean a connection to the customer has been established.", "连接在 SaaS 外部完成，打开 TeamViewer 不代表已连接客户设备。"],
  loading: ["Consultando intervención…", "Loading intervention…", "正在查询处理流程…"],
  reload: ["Actualizar intervención", "Refresh intervention", "刷新处理流程"],
  readError: ["No se pudo consultar la intervención. Actualiza antes de operar.", "Could not load intervention state. Refresh before taking action.", "无法获取处理状态，请刷新后再操作。"],
  writeError: ["No se pudo confirmar la solicitud. Reintenta la misma solicitud o actualiza para comprobarla.", "The request could not be confirmed. Retry the same request or refresh to check it.", "请求结果尚未确认，请重试同一请求或刷新核对。"],
  conflict: ["La intervención o el ticket ha cambiado. Actualiza y revisa la fase antes de volver a solicitar la acción.", "The intervention or ticket changed. Refresh and review the stage before requesting the action again.", "处理流程或工单状态已变化，请刷新并核对当前阶段后重新操作。"],
  rejected: ["El servidor rechazó la solicitud. Actualiza el estado antes de intentarlo de nuevo.", "The server rejected the request. Refresh the state before trying again.", "服务器拒绝了请求，请刷新状态后再试。"],
  pending: ["Hay una solicitud sin confirmar; se conservarán su identificador, nota y versión al reintentar.", "A request is unconfirmed; retries preserve its identifier, note and version.", "有待确认请求，重试将保留原标识、备注和版本。"],
  retry: ["Reintentar intervención pendiente", "Retry pending intervention", "重试待确认处理操作"],
  saved: ["Intervención registrada.", "Intervention recorded.", "处理记录已保存。"],
  permission: ["No tienes permiso para registrar intervenciones.", "You do not have permission to record interventions.", "你没有记录处理操作的权限。"],
  history: ["Historial de intervenciones", "Intervention history", "处理历史"],
  noHistory: ["Aún no hay intervenciones registradas.", "No interventions recorded yet.", "暂无处理记录。"],
  actor: ["Responsable", "Operator", "操作人"],
  time: ["Fecha", "Time", "时间"],
  unknown: ["Estado no reconocido; actualiza o consulta con un administrador.", "Unrecognized state; refresh or contact an administrator.", "未识别的状态，请刷新或联系管理员。"],
  REMOTE_PENDING: ["Pendiente de diagnóstico y asistencia","Awaiting diagnosis and assistance","等待诊断和协助"],
  REMOTE_IN_PROGRESS: ["Asistencia remota en curso", "Remote assistance in progress", "远程协助中"],
  ONSITE_REQUIRED: ["Requiere visita presencial", "On-site visit required", "需要现场处理"],
  ONSITE_IN_PROGRESS: ["Visita presencial en curso", "On-site visit in progress", "现场处理中"],
  RESOLVED: ["Intervención resuelta", "Intervention resolved", "处理已完成"],
  START_REMOTE: ["Iniciar asistencia remota", "Start remote assistance", "开始远程协助"],
  REQUIRE_ONSITE: ["Derivar a visita presencial", "Require on-site visit", "转现场处理"],
  START_ONSITE: ["Iniciar visita presencial", "Start on-site visit", "开始现场处理"],
  RESOLVE: ["Resolver intervención", "Resolve intervention", "完成处理"],
  REOPEN: ["Reabrir intervención", "Reopen intervention", "重新打开处理流程"],
} as const;
export function useInterventionLabels() {
  const { language } = useI18n();
  return (key: string) => (labels[key as keyof typeof labels] ?? labels.unknown)[language === "es" ? 0 : language === "en" ? 1 : 2];
}
