import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { ApiConnectionError, ApiError, apiRequest, type LocaleCode } from "@tpverp/app-common";
import {
  hydratePdaWorkDraft, hydratePdaWorkQueue, isAssignedToCurrentUser, isQueueConflict,
  nextQueueWakeup, queueRetryDelay, readPdaWorkDraft, readPdaWorkQueue, rememberLastWork,
  sendQueuedWork, shouldRetryQueueError, writePdaWorkDraft, writePdaWorkQueue, type WorkQueueEntry
} from "./PdaWorkQueue";

export { readPdaWorkQueue, writePdaWorkQueue } from "./PdaWorkQueue";

type WorkType = "INCIDENT" | "PICKING" | "REPLENISHMENT" | "LOT_CHECK" | "TASK";
type WorkStatus = "OPEN" | "PENDING" | "IN_PROGRESS" | "DONE" | "CANCELLED";
type WorkEvidence={id:string;name:string;contentType:string;createdAt:string};
type FefoAllocation={lotId:string;lotNumber:string;expiryDate?:string|null;quantity:number|string;version:number};
type WorkItem = { id:string; type:WorkType; status:WorkStatus; title:string; reference?:string|null; productCode?:string|null; warehouseId?:string|null; quantity?:number|null; lotNumber?:string|null; expiryDate?:string|null; location?:string|null; sourceLocation?:string|null; destinationLocation?:string|null; sourceLocationValidatedAt?:string|null; destinationLocationValidatedAt?:string|null; dueAt?:string|null; goodsCheckId?:string|null; documentId?:string|null; productId?:string|null; priority:string; notes?:string|null; evidenceName?:string|null; evidenceType?:string|null; evidenceData?:string|null; evidences?:WorkEvidence[]; createdAt:string; completedAt?:string|null; startedAt?:string|null; assignedTo?:string|null; assignedUserId?:string|null; version?:number|null };
type CreateWork = Omit<WorkItem,"id"|"status"|"createdAt"|"completedAt"|"assignedTo"|"assignedUserId"|"version">;
type WarehouseOption={id:string;name?:string|null;nombre?:string|null};

const copy={
 es:{title:"Operaciones de almacén",subtitle:"Incidencias, preparación, lotes y tareas en un único panel.",dashboard:"Panel",incident:"Incidencia",picking:"Preparación",replenishment:"Reposición",lot:"Lotes",task:"Tarea",open:"Mis pendientes",done:"Completadas",urgent:"Mis urgentes",queued:"Sin sincronizar",newIncident:"Registrar incidencia",newPicking:"Preparar pedido",newReplenishment:"Asignar reposición",newLot:"Controlar lote",newTask:"Crear tarea",name:"Título",reference:"Referencia / proveedor",product:"Producto o código",warehouse:"Almacén",quantity:"Cantidad",location:"Ubicación",lotNumber:"Número de lote",expiry:"Caducidad",priority:"Prioridad",normal:"Normal",high:"Alta",critical:"Urgente",notes:"Notas",photo:"Fotografía",save:"Guardar",start:"Iniciar",validateSource:"Validar origen",validateDestination:"Validar destino",addEvidence:"Añadir evidencia",source:"Ubicación origen",destination:"Ubicación destino",due:"Fecha límite",linkCheck:"Comprobación vinculada",linkDocument:"Documento vinculado",linkProduct:"Producto vinculado",registerLot:"Registrar entrada de lote",planFefo:"Planificar salida FEFO",fefoTitle:"Orden de salida FEFO",finish:"Completar",cancel:"Cancelar",refresh:"Actualizar",sync:"Sincronizar ahora",empty:"No hay operaciones en este filtro.",saved:"Operación guardada.",queuedMessage:"Sin conexión: acción guardada en la cola.",synced:"Cola sincronizada.",error:"No se pudo completar la operación.",storageError:"No se pudo guardar sin conexión. Mantén esta pantalla abierta y vuelve a intentarlo.",photoTooLarge:"La foto no puede superar 700 KB.",online:"En línea",offline:"Sin conexión",expiresSoon:"Caduca pronto",conflicts:"Conflictos",retry:"Reintentar",discard:"Descartar",nextRetry:"Próximo intento",attempts:"Intentos",syncing:"Sincronizando",conflictHelp:"El servidor cambió esta operación. Revisa y vuelve a intentar.",lastSync:"Última sincronización"},
 en:{title:"Warehouse operations",subtitle:"Incidents, picking, lots and tasks in one panel.",dashboard:"Dashboard",incident:"Incident",picking:"Picking",replenishment:"Replenishment",lot:"Lots",task:"Task",open:"My open tasks",done:"Completed",urgent:"My urgent tasks",queued:"Not synced",newIncident:"Report incident",newPicking:"Prepare order",newReplenishment:"Assign replenishment",newLot:"Check lot",newTask:"Create task",name:"Title",reference:"Reference / supplier",product:"Product or code",warehouse:"Warehouse",quantity:"Quantity",location:"Location",lotNumber:"Lot number",expiry:"Expiry date",priority:"Priority",normal:"Normal",high:"High",critical:"Urgent",notes:"Notes",photo:"Photo",save:"Save",start:"Start",validateSource:"Validate source",validateDestination:"Validate destination",addEvidence:"Add evidence",source:"Source location",destination:"Destination location",due:"Due date",linkCheck:"Linked goods check",linkDocument:"Linked document",linkProduct:"Linked product",registerLot:"Receive lot",planFefo:"Plan FEFO picking",fefoTitle:"FEFO picking order",finish:"Complete",cancel:"Cancel",refresh:"Refresh",sync:"Sync now",empty:"No operations in this filter.",saved:"Operation saved.",queuedMessage:"Offline: action saved to queue.",synced:"Queue synchronized.",error:"Operation could not be completed.",storageError:"Offline data could not be saved. Keep this screen open and retry.",photoTooLarge:"Photo must not exceed 700 KB.",online:"Online",offline:"Offline",expiresSoon:"Expires soon",conflicts:"Conflicts",retry:"Retry",discard:"Discard",nextRetry:"Next attempt",attempts:"Attempts",syncing:"Synchronizing",conflictHelp:"The server changed this operation. Review it and retry.",lastSync:"Last synchronization"},
 zh:{title:"仓库操作",subtitle:"在一个面板中处理异常、拣货、批次和任务。",dashboard:"面板",incident:"异常",picking:"拣货",replenishment:"补货",lot:"批次",task:"任务",open:"我的待处理",done:"已完成",urgent:"我的紧急任务",queued:"未同步",newIncident:"登记异常",newPicking:"准备订单",newReplenishment:"分配补货",newLot:"检查批次",newTask:"创建任务",name:"标题",reference:"参考 / 供应商",product:"商品或编码",warehouse:"仓库",quantity:"数量",location:"库位",lotNumber:"批次号",expiry:"有效期",priority:"优先级",normal:"普通",high:"高",critical:"紧急",notes:"备注",photo:"照片",save:"保存",start:"开始",validateSource:"验证来源库位",validateDestination:"验证目标库位",addEvidence:"添加凭证",source:"来源库位",destination:"目标库位",due:"截止时间",linkCheck:"关联验货",linkDocument:"关联单据",linkProduct:"关联商品",registerLot:"登记批次入库",planFefo:"规划 FEFO 出库",fefoTitle:"FEFO 出库顺序",finish:"完成",cancel:"取消",refresh:"刷新",sync:"立即同步",empty:"此筛选没有操作。",saved:"操作已保存。",queuedMessage:"离线：操作已保存到队列。",synced:"队列已同步。",error:"无法完成操作。",storageError:"无法保存离线数据。请保持此页面打开并重试。",photoTooLarge:"照片不能超过 700 KB。",online:"在线",offline:"离线",expiresSoon:"即将到期",conflicts:"冲突",retry:"重试",discard:"放弃",nextRetry:"下次尝试",attempts:"尝试次数",syncing:"正在同步",conflictHelp:"服务器上的操作已变化，请检查后重试。",lastSync:"上次同步"}
} as const;

const emptyForm:CreateWork={type:"TASK",title:"",reference:"",productCode:"",warehouseId:null,quantity:null,lotNumber:"",expiryDate:null,location:"",priority:"NORMAL",notes:"",evidenceName:null,evidenceType:null,evidenceData:null};
const LAST_SYNC_KEY="tpverp.pda.lastSyncAt.v1";
function queueEntry(action:"finish"|"cancel", item:WorkItem):WorkQueueEntry { return {id:crypto.randomUUID(),createdAt:new Date().toISOString(),action,workId:item.id,attempts:0,state:"pending",version:item.version}; }
function queueErrorText(error:unknown){return error instanceof ApiError||error instanceof ApiConnectionError?error.message:"sync_error"}
function isOpenWork(item:WorkItem){return item.status==="OPEN"||item.status==="PENDING"||item.status==="IN_PROGRESS"}

export function PdaWorkboard({token,locale,warehouses}:{token?:string;locale:LocaleCode;warehouses:WarehouseOption[]}){
 const c=copy[locale];
 const [tab,setTab]=useState<"dashboard"|WorkType>("dashboard");
 const [items,setItems]=useState<WorkItem[]>([]); const [form,setForm]=useState<CreateWork>(()=>readPdaWorkDraft<CreateWork>()??emptyForm);
 const [queue,setQueue]=useState<WorkQueueEntry[]>(()=>readPdaWorkQueue()); const [online,setOnline]=useState(navigator.onLine);
 const [persistenceReady,setPersistenceReady]=useState(false);
 const [busy,setBusy]=useState(false); const [fefo,setFefo]=useState<FefoAllocation[]>([]); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [syncing,setSyncing]=useState(false);
 const [now,setNow]=useState(Date.now()); const [lastSync,setLastSync]=useState(()=>localStorage.getItem(LAST_SYNC_KEY)??"");
 const localeTag=locale==="zh"?"zh-CN":locale==="en"?"en-GB":"es-ES"; const date=useMemo(()=>new Intl.DateTimeFormat(localeTag,{dateStyle:"medium",timeStyle:"short"}),[localeTag]);
 const warehouseName=(id?:string|null)=>warehouses.find(x=>x.id===id)?.name??warehouses.find(x=>x.id===id)?.nombre??id??"—";
 const load=useCallback(async()=>{if(!token||!navigator.onLine)return;setBusy(true);setError("");try{setItems(await apiRequest<WorkItem[]>("/pda-work",{token}))}catch{setError(c.error)}finally{setBusy(false)}},[c.error,token]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{let active=true;void Promise.all([hydratePdaWorkQueue(),hydratePdaWorkDraft<CreateWork>()]).then(([storedQueue,draft])=>{if(!active)return;setQueue(storedQueue);if(draft)setForm(draft);setPersistenceReady(true)});return()=>{active=false}},[]);
 useEffect(()=>{if(!persistenceReady)return;const timer=window.setTimeout(()=>writePdaWorkDraft(form),300);return()=>clearTimeout(timer)},[form,persistenceReady]);
 useEffect(()=>{const failed=()=>setError(c.storageError);window.addEventListener("pda-durable-storage-error",failed);return()=>window.removeEventListener("pda-durable-storage-error",failed)},[c.storageError]);
 useEffect(()=>{const clock=window.setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(clock)},[]);
 function persistQueue(values:WorkQueueEntry[]){setQueue(values);writePdaWorkQueue(values)}
 const syncQueue=useCallback(async(force=false)=>{if(!token||!navigator.onLine||syncing)return;const current=readPdaWorkQueue();const due=current.filter(entry=>entry.state!=="conflict"&&(force||!entry.nextRetryAt||new Date(entry.nextRetryAt).getTime()<=Date.now()));if(!due.length)return;setSyncing(true);setError("");let next=[...current];let changed=false;for(const entry of due){try{const value=await sendQueuedWork<WorkItem>(entry,token);next=next.filter(item=>item.id!==entry.id);changed=true;setItems(values=>entry.action==="create"?[value,...values]:values.map(item=>item.id===value.id?value:item));rememberLastWork(value)}catch(cause){const attempts=entry.attempts+1;const conflict=isQueueConflict(cause)||!shouldRetryQueueError(cause);next=next.map(item=>item.id===entry.id?{...item,attempts,state:conflict?"conflict":"pending",lastError:queueErrorText(cause),nextRetryAt:conflict?null:new Date(Date.now()+queueRetryDelay(attempts)).toISOString()}:item);changed=true;}}if(changed)persistQueue(next);if(next.length===0){const value=new Date().toISOString();localStorage.setItem(LAST_SYNC_KEY,value);setLastSync(value);setMessage(c.synced);await load()}setSyncing(false)},[c.synced,load,syncing,token]);
 useEffect(()=>{const up=()=>{setOnline(true);void syncQueue()},down=()=>setOnline(false);window.addEventListener("online",up);window.addEventListener("offline",down);return()=>{window.removeEventListener("online",up);window.removeEventListener("offline",down)}},[syncQueue]);
 useEffect(()=>{if(!online||!token)return;const delay=nextQueueWakeup(queue);if(delay==null)return;const timer=window.setTimeout(()=>void syncQueue(),Math.min(delay,2_147_000_000));return()=>clearTimeout(timer)},[online,queue,syncQueue,token]);
 function select(next:"dashboard"|WorkType){setTab(next);if(next!=="dashboard")setForm({...emptyForm,type:next})}
 function enqueue(entry:WorkQueueEntry){persistQueue([...readPdaWorkQueue(),entry]);setMessage(c.queuedMessage)}
 async function submit(event:FormEvent){event.preventDefault();if(!token||!form.title.trim())return;setBusy(true);setError("");setMessage("");const payload={...form,title:form.title.trim(),quantity:form.quantity==null?null:Number(form.quantity)};if(!navigator.onLine){enqueue({id:crypto.randomUUID(),createdAt:new Date().toISOString(),action:"create",payload,attempts:0,state:"pending"});setForm({...emptyForm,type:form.type});setBusy(false);return}try{const saved=await apiRequest<WorkItem>("/pda-work",{token,body:payload});setItems(current=>[saved,...current]);rememberLastWork(saved);setForm({...emptyForm,type:form.type});setMessage(c.saved)}catch(cause){if(shouldRetryQueueError(cause)){enqueue({id:crypto.randomUUID(),createdAt:new Date().toISOString(),action:"create",payload,attempts:1,state:"pending",lastError:queueErrorText(cause),nextRetryAt:new Date(Date.now()+queueRetryDelay(1)).toISOString()});setForm({...emptyForm,type:form.type})}else setError(c.error)}finally{setBusy(false)}}
 async function close(item:WorkItem,action:"finish"|"cancel"){if(!token)return;rememberLastWork(item);if(!navigator.onLine){enqueue(queueEntry(action,item));setItems(values=>values.map(value=>value.id===item.id?{...value,status:action==="finish"?"DONE":"CANCELLED"}:value));return}setBusy(true);setError("");try{const value=await apiRequest<WorkItem>(`/pda-work/${encodeURIComponent(item.id)}/${action}`,{method:"POST",token,...(item.version==null?{}:{body:{version:item.version}})});setItems(current=>current.map(entry=>entry.id===item.id?value:entry));rememberLastWork(value)}catch(cause){if(shouldRetryQueueError(cause)||isQueueConflict(cause))enqueue({...queueEntry(action,item),state:isQueueConflict(cause)?"conflict":"pending",attempts:1,lastError:queueErrorText(cause),nextRetryAt:isQueueConflict(cause)?null:new Date(Date.now()+queueRetryDelay(1)).toISOString()});else setError(c.error)}finally{setBusy(false)}}
 async function receiveLot(){if(!token||!form.warehouseId||!form.productCode?.trim()||!form.lotNumber?.trim()||form.quantity==null)return;setBusy(true);setError("");try{await apiRequest("/pda-inventory/lots",{method:"POST",token,body:{warehouseId:form.warehouseId,productId:form.productId||null,productCode:form.productCode.trim(),lotNumber:form.lotNumber.trim(),expiryDate:form.expiryDate||null,supplierId:null,supplierReference:form.reference||null,quantity:Number(form.quantity)}});setMessage(c.saved);await planFefo()}catch{setError(c.error)}finally{setBusy(false)}}
 async function planFefo(){if(!token||!form.warehouseId||!form.productCode?.trim()||!form.quantity||Number(form.quantity)<=0)return;setBusy(true);setError("");try{setFefo(await apiRequest<FefoAllocation[]>(`/pda-inventory/lots/fefo?warehouseId=${encodeURIComponent(form.warehouseId)}&productCode=${encodeURIComponent(form.productCode.trim())}&quantity=${encodeURIComponent(String(form.quantity))}`,{token}))}catch{setError(c.error)}finally{setBusy(false)}}
 async function photo(file?:File){if(!file)return;if(file.size>700_000){setError(c.photoTooLarge);return}const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)});setForm(current=>({...current,evidenceName:file.name,evidenceType:file.type,evidenceData:data}))}
 async function startWork(item:WorkItem){if(!token||!navigator.onLine)return;setBusy(true);setError("");try{const value=await apiRequest<WorkItem>(`/pda-work/${encodeURIComponent(item.id)}/start`,{method:"POST",token,...(item.version==null?{}:{body:{version:item.version}})});setItems(current=>current.map(entry=>entry.id===item.id?value:entry));rememberLastWork(value)}catch{setError(c.error)}finally{setBusy(false)}}
 async function validateLocation(item:WorkItem,role:"SOURCE"|"DESTINATION"){if(!token||!navigator.onLine)return;const expected=role==="SOURCE"?item.sourceLocation:item.destinationLocation;const code=window.prompt(role==="SOURCE"?c.validateSource:c.validateDestination,expected??"")?.trim();if(!code)return;setBusy(true);setError("");try{const value=await apiRequest<WorkItem>(`/pda-work/${encodeURIComponent(item.id)}/validate-location`,{method:"POST",token,body:{code,role,version:item.version}});setItems(current=>current.map(entry=>entry.id===item.id?value:entry));rememberLastWork(value)}catch{setError(c.error)}finally{setBusy(false)}}
 async function uploadEvidence(item:WorkItem,file?:File){if(!token||!file)return;if(file.size>700_000){setError(c.photoTooLarge);return}const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)});setBusy(true);setError("");try{await apiRequest(`/pda-work/${encodeURIComponent(item.id)}/evidences`,{method:"POST",token,body:{name:file.name,contentType:file.type||"application/octet-stream",data,version:item.version}});await load()}catch{setError(c.error)}finally{setBusy(false)}}
 function retry(id:string){persistQueue(readPdaWorkQueue().map(entry=>entry.id===id?{...entry,state:"pending",nextRetryAt:null,lastError:null}:entry));void syncQueue(true)}
 function discard(id:string){persistQueue(readPdaWorkQueue().filter(entry=>entry.id!==id))}
 const ownItems=items.filter(item=>isAssignedToCurrentUser(item,token)); const visible=tab==="dashboard"?ownItems:ownItems.filter(item=>item.type===tab);
 const open=ownItems.filter(isOpenWork).length,done=ownItems.filter(x=>x.status==="DONE").length,urgent=ownItems.filter(x=>isOpenWork(x)&&x.priority==="CRITICAL").length;
 const expiring=ownItems.filter(x=>x.type==="LOT_CHECK"&&isOpenWork(x)&&x.expiryDate&&new Date(x.expiryDate).getTime()<Date.now()+30*86400000).length; const conflicts=queue.filter(x=>x.state==="conflict").length;
 const retryAt=queue.filter(x=>x.state!=="conflict"&&x.nextRetryAt).map(x=>new Date(x.nextRetryAt!).getTime()).sort((a,b)=>a-b)[0];
 return <section className="pda-workboard">
  <header><div><span>{online?c.online:c.offline}</span><h2>{c.title}</h2><p>{c.subtitle}</p>{lastSync&&<small>{c.lastSync}: {date.format(new Date(lastSync))}</small>}</div><div><button disabled={busy} onClick={()=>void load()}>{c.refresh}</button><button disabled={syncing||queue.length===0||!online} onClick={()=>void syncQueue(true)}>{syncing?c.syncing:c.sync} ({queue.length})</button></div></header>
  <nav>{[["dashboard",c.dashboard],["INCIDENT",c.incident],["PICKING",c.picking],["REPLENISHMENT",c.replenishment],["LOT_CHECK",c.lot],["TASK",c.task]].map(([value,label])=><button key={value} className={tab===value?"active":""} onClick={()=>select(value as "dashboard"|WorkType)}>{label}</button>)}</nav>
  {message&&<p className="pda-count-status" role="status">{message}</p>}{error&&<p className="pda-count-error" role="alert">{error}</p>}
  {tab==="dashboard"&&<section className="pda-work-kpis"><div><span>{c.open}</span><b>{open}</b></div><div><span>{c.done}</span><b>{done}</b></div><div className="urgent"><span>{c.urgent}</span><b>{urgent}</b></div><div><span>{c.queued}</span><b>{queue.length}</b>{retryAt&&<small>{c.nextRetry}: {Math.max(0,Math.ceil((retryAt-now)/1000))}s</small>}</div><div className="expiry"><span>{c.expiresSoon}</span><b>{expiring}</b></div></section>}
  {queue.length>0&&<section className="pda-work-queue"><header><strong>{c.queued}: {queue.length}</strong>{conflicts>0&&<span>{c.conflicts}: {conflicts}</span>}</header>{queue.map(entry=><article key={entry.id} className={entry.state}><div><b>{entry.action}</b><small>{c.attempts}: {entry.attempts}{entry.lastError?` · ${entry.lastError}`:""}</small>{entry.state==="conflict"&&<small>{c.conflictHelp}</small>}</div><footer><button onClick={()=>discard(entry.id)}>{c.discard}</button><button disabled={!online} onClick={()=>retry(entry.id)}>{c.retry}</button></footer></article>)}</section>}
  {tab!=="dashboard"&&<form onSubmit={submit} className="pda-work-form"><h3>{tab==="INCIDENT"?c.newIncident:tab==="PICKING"?c.newPicking:tab==="REPLENISHMENT"?c.newReplenishment:tab==="LOT_CHECK"?c.newLot:c.newTask}</h3>
   <label><span>{c.name}</span><input required maxLength={180} value={form.title} onChange={e=>setForm(x=>({...x,title:e.target.value}))}/></label>
   {tab!=="TASK"&&<label><span>{c.reference}</span><input maxLength={120} value={form.reference??""} onChange={e=>setForm(x=>({...x,reference:e.target.value}))}/></label>}
   {(tab==="PICKING"||tab==="REPLENISHMENT"||tab==="LOT_CHECK")&&<><label><span>{c.product}</span><input maxLength={120} value={form.productCode??""} onChange={e=>setForm(x=>({...x,productCode:e.target.value}))}/></label><label><span>{c.warehouse}</span><select value={form.warehouseId??""} onChange={e=>setForm(x=>({...x,warehouseId:e.target.value||null}))}><option value="">—</option>{warehouses.map(w=><option key={w.id} value={w.id}>{warehouseName(w.id)}</option>)}</select></label><label><span>{c.quantity}</span><input type="number" min="0" step="0.001" value={form.quantity??""} onChange={e=>setForm(x=>({...x,quantity:e.target.value===""?null:Number(e.target.value)}))}/></label></>}
   {tab==="PICKING"&&<label><span>{c.location}</span><input maxLength={120} value={form.location??""} onChange={e=>setForm(x=>({...x,location:e.target.value}))}/></label>}
   {tab==="REPLENISHMENT"&&<><label><span>{c.source}</span><input maxLength={120} value={form.sourceLocation??""} onChange={e=>setForm(x=>({...x,sourceLocation:e.target.value}))}/></label><label><span>{c.destination}</span><input maxLength={120} value={form.destinationLocation??""} onChange={e=>setForm(x=>({...x,destinationLocation:e.target.value}))}/></label><label><span>{c.due}</span><input type="datetime-local" value={form.dueAt?.slice(0,16)??""} onChange={e=>setForm(x=>({...x,dueAt:e.target.value?new Date(e.target.value).toISOString():null}))}/></label></>}
   {tab==="INCIDENT"&&<><label><span>{c.linkCheck}</span><input value={form.goodsCheckId??""} onChange={e=>setForm(x=>({...x,goodsCheckId:e.target.value||null}))}/></label><label><span>{c.linkDocument}</span><input value={form.documentId??""} onChange={e=>setForm(x=>({...x,documentId:e.target.value||null}))}/></label><label><span>{c.linkProduct}</span><input value={form.productId??""} onChange={e=>setForm(x=>({...x,productId:e.target.value||null}))}/></label></>}
   {tab==="LOT_CHECK"&&<><label><span>{c.lotNumber}</span><input maxLength={120} value={form.lotNumber??""} onChange={e=>setForm(x=>({...x,lotNumber:e.target.value}))}/></label><label><span>{c.expiry}</span><input type="date" value={form.expiryDate??""} onChange={e=>setForm(x=>({...x,expiryDate:e.target.value||null}))}/></label></>}
   <label><span>{c.priority}</span><select value={form.priority} onChange={e=>setForm(x=>({...x,priority:e.target.value}))}><option value="NORMAL">{c.normal}</option><option value="HIGH">{c.high}</option><option value="CRITICAL">{c.critical}</option></select></label>
   <label className="wide"><span>{c.notes}</span><textarea maxLength={4000} value={form.notes??""} onChange={e=>setForm(x=>({...x,notes:e.target.value}))}/></label>
   {tab==="INCIDENT"&&<label className="wide"><span>{c.photo}</span><input type="file" accept="image/*" capture="environment" onChange={e=>void photo(e.target.files?.[0])}/></label>}
   {tab==="LOT_CHECK"&&<div className="wide pda-work-lot-actions"><button type="button" disabled={busy} onClick={()=>void receiveLot()}>{c.registerLot}</button><button type="button" disabled={busy} onClick={()=>void planFefo()}>{c.planFefo}</button></div>}
   <button className="wide primary" disabled={busy}>{c.save}</button>
  </form>}
  {tab==="LOT_CHECK"&&fefo.length>0&&<section className="pda-work-fefo"><h3>{c.fefoTitle}</h3>{fefo.map((allocation,index)=><article key={allocation.lotId}><b>{index+1}. {allocation.lotNumber}</b><span>{allocation.expiryDate??"—"}</span><strong>{allocation.quantity}</strong></article>)}</section>}
  <section className="pda-work-list">{visible.length===0&&<p>{c.empty}</p>}{visible.map(item=><article key={item.id} className={`priority-${item.priority.toLowerCase()} status-${item.status.toLowerCase()}`} onClick={()=>rememberLastWork(item)}><header><span>{item.type==="INCIDENT"?c.incident:item.type==="PICKING"?c.picking:item.type==="REPLENISHMENT"?c.replenishment:item.type==="LOT_CHECK"?c.lot:c.task}</span><strong>{item.title}</strong><time>{date.format(new Date(item.createdAt))}</time></header><div className="pda-work-meta">{item.reference&&<span>{item.reference}</span>}{item.productCode&&<span>{item.productCode}</span>}{item.warehouseId&&<span>{warehouseName(item.warehouseId)}</span>}{item.location&&<span>{item.location}</span>}{item.sourceLocation&&<span>→ {item.sourceLocation}{item.sourceLocationValidatedAt?" ✓":""}</span>}{item.destinationLocation&&<span>→ {item.destinationLocation}{item.destinationLocationValidatedAt?" ✓":""}</span>}{item.dueAt&&<span>{date.format(new Date(item.dueAt))}</span>}{item.lotNumber&&<span>{c.lotNumber}: {item.lotNumber}</span>}{item.expiryDate&&<span>{c.expiry}: {item.expiryDate}</span>}{item.quantity!=null&&<span>{c.quantity}: {item.quantity}</span>}</div>{item.notes&&<p>{item.notes}</p>}{item.evidenceData&&<img src={item.evidenceData} alt={item.evidenceName??c.photo}/>} {item.evidences&&item.evidences.length>0&&<small>{c.photo}: {item.evidences.length}</small>}{isOpenWork(item)&&<footer>{item.status==="PENDING"&&<button disabled={busy||!online} onClick={()=>void startWork(item)}>{c.start}</button>}{item.status==="IN_PROGRESS"&&item.sourceLocation&&!item.sourceLocationValidatedAt&&<button disabled={busy||!online} onClick={()=>void validateLocation(item,"SOURCE")}>{c.validateSource}</button>}{item.status==="IN_PROGRESS"&&item.destinationLocation&&!item.destinationLocationValidatedAt&&<button disabled={busy||!online} onClick={()=>void validateLocation(item,"DESTINATION")}>{c.validateDestination}</button>}<label className="pda-work-evidence"><span>{c.addEvidence}</span><input type="file" accept="image/*" capture="environment" disabled={busy||!online} onChange={event=>void uploadEvidence(item,event.currentTarget.files?.[0])}/></label><button disabled={busy} onClick={()=>void close(item,"cancel")}>{c.cancel}</button><button disabled={busy||item.status==="PENDING"} onClick={()=>void close(item,"finish")}>{c.finish}</button></footer>}</article>)}</section>
 </section>
}
