import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { apiRequest, type LocaleCode } from "@tpverp/app-common";

type WorkType = "INCIDENT" | "PICKING" | "LOT_CHECK" | "TASK";
type WorkStatus = "OPEN" | "DONE" | "CANCELLED";
type WorkItem = { id:string; type:WorkType; status:WorkStatus; title:string; reference?:string|null; productCode?:string|null; warehouseId?:string|null; quantity?:number|null; lotNumber?:string|null; expiryDate?:string|null; location?:string|null; priority:string; notes?:string|null; evidenceName?:string|null; evidenceType?:string|null; evidenceData?:string|null; createdAt:string; completedAt?:string|null };
type CreateWork = Omit<WorkItem,"id"|"status"|"createdAt"|"completedAt">;
type WarehouseOption={id:string;name?:string|null;nombre?:string|null};
type QueueEntry={id:string;createdAt:string;payload:CreateWork};
const QUEUE_KEY="tpverp.pda.work.queue.v1";

export function readPdaWorkQueue():QueueEntry[]{try{const value=JSON.parse(localStorage.getItem(QUEUE_KEY)??"[]");return Array.isArray(value)?value:[]}catch{return []}}
export function writePdaWorkQueue(values:QueueEntry[]){localStorage.setItem(QUEUE_KEY,JSON.stringify(values))}

const copy={
 es:{title:"Operaciones de almacén",subtitle:"Incidencias, preparación, lotes y tareas en un único panel.",dashboard:"Panel",incident:"Incidencia",picking:"Preparación",lot:"Lotes",task:"Tarea",open:"Pendientes",done:"Completadas",urgent:"Urgentes",queued:"Sin sincronizar",newIncident:"Registrar incidencia",newPicking:"Preparar pedido",newLot:"Controlar lote",newTask:"Crear tarea",name:"Título",reference:"Referencia / proveedor",product:"Producto o código",warehouse:"Almacén",quantity:"Cantidad",location:"Ubicación",lotNumber:"Número de lote",expiry:"Caducidad",priority:"Prioridad",normal:"Normal",high:"Alta",critical:"Urgente",notes:"Notas",photo:"Fotografía",save:"Guardar",finish:"Completar",cancel:"Cancelar",refresh:"Actualizar",sync:"Sincronizar",empty:"No hay operaciones en este filtro.",saved:"Operación guardada.",queuedMessage:"Sin conexión: operación guardada en la cola.",synced:"Cola sincronizada.",error:"No se pudo completar la operación.",photoTooLarge:"La foto no puede superar 700 KB.",online:"En línea",offline:"Sin conexión",expiresSoon:"Caduca pronto",all:"Todas"},
 en:{title:"Warehouse operations",subtitle:"Incidents, picking, lots and tasks in one panel.",dashboard:"Dashboard",incident:"Incident",picking:"Picking",lot:"Lots",task:"Task",open:"Open",done:"Completed",urgent:"Urgent",queued:"Not synced",newIncident:"Report incident",newPicking:"Prepare order",newLot:"Check lot",newTask:"Create task",name:"Title",reference:"Reference / supplier",product:"Product or code",warehouse:"Warehouse",quantity:"Quantity",location:"Location",lotNumber:"Lot number",expiry:"Expiry date",priority:"Priority",normal:"Normal",high:"High",critical:"Urgent",notes:"Notes",photo:"Photo",save:"Save",finish:"Complete",cancel:"Cancel",refresh:"Refresh",sync:"Sync",empty:"No operations in this filter.",saved:"Operation saved.",queuedMessage:"Offline: operation saved to queue.",synced:"Queue synchronized.",error:"Operation could not be completed.",photoTooLarge:"Photo must not exceed 700 KB.",online:"Online",offline:"Offline",expiresSoon:"Expires soon",all:"All"},
 zh:{title:"仓库操作",subtitle:"在一个面板中处理异常、拣货、批次和任务。",dashboard:"面板",incident:"异常",picking:"拣货",lot:"批次",task:"任务",open:"待处理",done:"已完成",urgent:"紧急",queued:"未同步",newIncident:"登记异常",newPicking:"准备订单",newLot:"检查批次",newTask:"创建任务",name:"标题",reference:"参考 / 供应商",product:"商品或编码",warehouse:"仓库",quantity:"数量",location:"库位",lotNumber:"批次号",expiry:"有效期",priority:"优先级",normal:"普通",high:"高",critical:"紧急",notes:"备注",photo:"照片",save:"保存",finish:"完成",cancel:"取消",refresh:"刷新",sync:"同步",empty:"此筛选没有操作。",saved:"操作已保存。",queuedMessage:"离线：操作已保存到队列。",synced:"队列已同步。",error:"无法完成操作。",photoTooLarge:"照片不能超过 700 KB。",online:"在线",offline:"离线",expiresSoon:"即将到期",all:"全部"}
} as const;

const emptyForm:CreateWork={type:"TASK",title:"",reference:"",productCode:"",warehouseId:null,quantity:null,lotNumber:"",expiryDate:null,location:"",priority:"NORMAL",notes:"",evidenceName:null,evidenceType:null,evidenceData:null};

export function PdaWorkboard({token,locale,warehouses}:{token?:string;locale:LocaleCode;warehouses:WarehouseOption[]}){
 const c=copy[locale];
 const [tab,setTab]=useState<"dashboard"|WorkType>("dashboard");
 const [items,setItems]=useState<WorkItem[]>([]); const [form,setForm]=useState<CreateWork>(emptyForm);
 const [queue,setQueue]=useState<QueueEntry[]>(()=>readPdaWorkQueue()); const [online,setOnline]=useState(navigator.onLine);
 const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
 const localeTag=locale==="zh"?"zh-CN":locale==="en"?"en-GB":"es-ES"; const date=useMemo(()=>new Intl.DateTimeFormat(localeTag,{dateStyle:"medium",timeStyle:"short"}),[localeTag]);
 const warehouseName=(id?:string|null)=>warehouses.find(x=>x.id===id)?.name??warehouses.find(x=>x.id===id)?.nombre??id??"—";
 const load=useCallback(async()=>{if(!token)return;setBusy(true);setError("");try{setItems(await apiRequest<WorkItem[]>("/pda-work",{token}))}catch{setError(c.error)}finally{setBusy(false)}},[c.error,token]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{const up=()=>setOnline(true),down=()=>setOnline(false);window.addEventListener("online",up);window.addEventListener("offline",down);return()=>{window.removeEventListener("online",up);window.removeEventListener("offline",down)}},[]);
 function select(next:"dashboard"|WorkType){setTab(next);if(next!=="dashboard")setForm({...emptyForm,type:next})}
 function persistQueue(values:QueueEntry[]){setQueue(values);writePdaWorkQueue(values)}
 async function syncQueue(){if(!token||!navigator.onLine||queue.length===0)return;setBusy(true);setError("");const pending=[...queue];const failed:QueueEntry[]=[];for(const entry of pending){try{await apiRequest<WorkItem>("/pda-work",{token,body:entry.payload})}catch{failed.push(entry)}}persistQueue(failed);setMessage(failed.length?c.error:c.synced);await load();setBusy(false)}
 async function submit(event:FormEvent){event.preventDefault();if(!token||!form.title.trim())return;setBusy(true);setError("");setMessage("");const payload={...form,title:form.title.trim(),quantity:form.quantity==null?null:Number(form.quantity)};try{const saved=await apiRequest<WorkItem>("/pda-work",{token,body:payload});setItems(current=>[saved,...current]);setForm({...emptyForm,type:form.type});setMessage(c.saved)}catch{const entry={id:crypto.randomUUID(),createdAt:new Date().toISOString(),payload};persistQueue([...queue,entry]);setForm({...emptyForm,type:form.type});setMessage(c.queuedMessage)}finally{setBusy(false)}}
 async function close(id:string,action:"finish"|"cancel"){if(!token)return;setBusy(true);setError("");try{const value=await apiRequest<WorkItem>(`/pda-work/${encodeURIComponent(id)}/${action}`,{method:"POST",token});setItems(current=>current.map(item=>item.id===id?value:item))}catch{setError(c.error)}finally{setBusy(false)}}
 async function photo(file?:File){if(!file)return;if(file.size>700_000){setError(c.photoTooLarge);return}const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)});setForm(current=>({...current,evidenceName:file.name,evidenceType:file.type,evidenceData:data}))}
 const visible=tab==="dashboard"?items:items.filter(item=>item.type===tab);
 const open=items.filter(x=>x.status==="OPEN").length,done=items.filter(x=>x.status==="DONE").length,urgent=items.filter(x=>x.status==="OPEN"&&x.priority==="CRITICAL").length;
 const expiring=items.filter(x=>x.type==="LOT_CHECK"&&x.status==="OPEN"&&x.expiryDate&&new Date(x.expiryDate).getTime()<Date.now()+30*86400000).length;
 return <section className="pda-workboard">
  <header><div><span>{online?c.online:c.offline}</span><h2>{c.title}</h2><p>{c.subtitle}</p></div><div><button disabled={busy} onClick={()=>void load()}>{c.refresh}</button><button disabled={busy||queue.length===0||!online} onClick={()=>void syncQueue()}>{c.sync} ({queue.length})</button></div></header>
  <nav>{[["dashboard",c.dashboard],["INCIDENT",c.incident],["PICKING",c.picking],["LOT_CHECK",c.lot],["TASK",c.task]].map(([value,label])=><button key={value} className={tab===value?"active":""} onClick={()=>select(value as "dashboard"|WorkType)}>{label}</button>)}</nav>
  {message&&<p className="pda-count-status" role="status">{message}</p>}{error&&<p className="pda-count-error" role="alert">{error}</p>}
  {tab==="dashboard"&&<section className="pda-work-kpis"><div><span>{c.open}</span><b>{open}</b></div><div><span>{c.done}</span><b>{done}</b></div><div className="urgent"><span>{c.urgent}</span><b>{urgent}</b></div><div><span>{c.queued}</span><b>{queue.length}</b></div><div className="expiry"><span>{c.expiresSoon}</span><b>{expiring}</b></div></section>}
  {tab!=="dashboard"&&<form onSubmit={submit} className="pda-work-form"><h3>{tab==="INCIDENT"?c.newIncident:tab==="PICKING"?c.newPicking:tab==="LOT_CHECK"?c.newLot:c.newTask}</h3>
   <label><span>{c.name}</span><input required maxLength={180} value={form.title} onChange={e=>setForm(x=>({...x,title:e.target.value}))}/></label>
   {tab!=="TASK"&&<label><span>{c.reference}</span><input maxLength={120} value={form.reference??""} onChange={e=>setForm(x=>({...x,reference:e.target.value}))}/></label>}
   {(tab==="PICKING"||tab==="LOT_CHECK")&&<><label><span>{c.product}</span><input maxLength={120} value={form.productCode??""} onChange={e=>setForm(x=>({...x,productCode:e.target.value}))}/></label><label><span>{c.warehouse}</span><select value={form.warehouseId??""} onChange={e=>setForm(x=>({...x,warehouseId:e.target.value||null}))}><option value="">—</option>{warehouses.map(w=><option key={w.id} value={w.id}>{warehouseName(w.id)}</option>)}</select></label><label><span>{c.quantity}</span><input type="number" min="0" step="0.001" value={form.quantity??""} onChange={e=>setForm(x=>({...x,quantity:e.target.value===""?null:Number(e.target.value)}))}/></label></>}
   {tab==="PICKING"&&<label><span>{c.location}</span><input maxLength={120} value={form.location??""} onChange={e=>setForm(x=>({...x,location:e.target.value}))}/></label>}
   {tab==="LOT_CHECK"&&<><label><span>{c.lotNumber}</span><input maxLength={120} value={form.lotNumber??""} onChange={e=>setForm(x=>({...x,lotNumber:e.target.value}))}/></label><label><span>{c.expiry}</span><input type="date" value={form.expiryDate??""} onChange={e=>setForm(x=>({...x,expiryDate:e.target.value||null}))}/></label></>}
   <label><span>{c.priority}</span><select value={form.priority} onChange={e=>setForm(x=>({...x,priority:e.target.value}))}><option value="NORMAL">{c.normal}</option><option value="HIGH">{c.high}</option><option value="CRITICAL">{c.critical}</option></select></label>
   <label className="wide"><span>{c.notes}</span><textarea maxLength={4000} value={form.notes??""} onChange={e=>setForm(x=>({...x,notes:e.target.value}))}/></label>
   {tab==="INCIDENT"&&<label className="wide"><span>{c.photo}</span><input type="file" accept="image/*" capture="environment" onChange={e=>void photo(e.target.files?.[0])}/></label>}
   <button className="wide primary" disabled={busy}>{c.save}</button>
  </form>}
  <section className="pda-work-list">{visible.length===0&&<p>{c.empty}</p>}{visible.map(item=><article key={item.id} className={`priority-${item.priority.toLowerCase()} status-${item.status.toLowerCase()}`}><header><span>{item.type==="INCIDENT"?c.incident:item.type==="PICKING"?c.picking:item.type==="LOT_CHECK"?c.lot:c.task}</span><strong>{item.title}</strong><time>{date.format(new Date(item.createdAt))}</time></header><div className="pda-work-meta">{item.reference&&<span>{item.reference}</span>}{item.productCode&&<span>{item.productCode}</span>}{item.warehouseId&&<span>{warehouseName(item.warehouseId)}</span>}{item.location&&<span>{item.location}</span>}{item.lotNumber&&<span>{c.lotNumber}: {item.lotNumber}</span>}{item.expiryDate&&<span>{c.expiry}: {item.expiryDate}</span>}{item.quantity!=null&&<span>{c.quantity}: {item.quantity}</span>}</div>{item.notes&&<p>{item.notes}</p>}{item.evidenceData&&<img src={item.evidenceData} alt={item.evidenceName??c.photo}/>} {item.status==="OPEN"&&<footer><button disabled={busy} onClick={()=>void close(item.id,"cancel")}>{c.cancel}</button><button disabled={busy} onClick={()=>void close(item.id,"finish")}>{c.finish}</button></footer>}</article>)}</section>
 </section>
}