import { useI18n } from "../../i18n";

const labels = {
  company: ["Empresa", "Company", "企业"],
  chooseCompany: ["Selecciona una empresa", "Select a company", "请选择企业"],
  chooseStores: ["Selecciona las tiendas que quieres consultar", "Select the stores to inspect", "请选择要查询的门店"],
  oneStore: ["Selecciona una sola tienda para esta consulta", "Select one store for this query", "此查询需要选择一个门店"],
  stores: ["Tiendas autorizadas", "Authorized stores", "已授权门店"],
  noAccess: ["SIN ACCESOS", "NO ACCESS", "暂无访问权限"],
  empty: ["SIN DATOS", "NO DATA", "暂无数据"],
  loading: ["Cargando…", "Loading…", "正在加载…"],
  refresh: ["Actualizar", "Refresh", "刷新"],
  logout: ["Salir", "Sign out", "退出"],
  supervision: ["Consulta de tiendas", "Store overview", "门店查询"],
  documents: ["Documentos", "Documents", "单据"],
  stock: ["Existencias", "Stock", "库存"],
  sync: ["Sincronización", "Synchronization", "同步"],
  readOnly: ["Consulta de datos recibidos de las tiendas", "Read data received from stores", "查询从门店收到的数据"],
  inactive: ["Inactiva", "Inactive", "停用"],
  type: ["Tipo", "Type", "类型"],
  status: ["Estado", "Status", "状态"],
  all: ["Todos", "All", "全部"],
  from: ["Desde", "From", "开始日期"],
  to: ["Hasta", "To", "结束日期"],
  number: ["Número", "Number", "编号"],
  date: ["Fecha", "Date", "日期"],
  store: ["Tienda", "Store", "门店"],
  customer: ["Cliente", "Customer", "客户"],
  total: ["Total", "Total", "总额"],
  search: ["Consultar", "Search", "查询"],
  previous: ["Anterior", "Previous", "上一页"],
  next: ["Siguiente", "Next", "下一页"],
  page: ["Página", "Page", "页"],
  product: ["Producto", "Product", "商品"],
  warehouse: ["Almacén", "Warehouse", "仓库"],
  quantity: ["Cantidad", "Quantity", "数量"],
  received: ["Pendientes de procesar", "Waiting to process", "待处理"],
  projected: ["Procesados", "Processed", "已处理"],
  ignored: ["Sin proyección", "Not projected", "未投影"],
  errors: ["Con error", "Failed", "失败"],
  oldest: ["Primer pendiente recibido", "Oldest pending receipt", "最早待处理接收时间"],
  conversation: ["Conversación de soporte", "Support conversation", "支持对话"],
  ticket: ["Solicitud", "Request", "请求"],
  message: ["Mensaje", "Message", "消息"],
  send: ["Enviar", "Send", "发送"],
  sent: ["Mensaje enviado", "Message sent", "消息已发送"],
  partialError: ["No se pudieron cargar todos los apartados", "Some sections could not be loaded", "部分页面无法加载"],
  TICKET: ["Ticket", "Receipt", "小票"],
  ALBARAN_VENTA: ["Albarán", "Delivery note", "送货单"],
  FACTURA_VENTA: ["Factura", "Invoice", "发票"],
  RECTIFICATIVA_VENTA: ["Rectificativa", "Credit note", "更正发票"],
  CONFIRMADO: ["Confirmado", "Confirmed", "已确认"],
  ANULADO: ["Anulado", "Cancelled", "已取消"],
  PENDIENTE: ["Pendiente", "Pending", "待处理"],
  PARCIAL: ["Parcial", "Partial", "部分完成"],
  PAGADO: ["Pagado", "Paid", "已支付"],
} as const;
export type TenantLabel = keyof typeof labels;
export function useTenantLabels() {
  const { language } = useI18n();
  const index = language === "zh" ? 2 : language === "en" ? 1 : 0;
  return (key: TenantLabel) => labels[key][index];
}
