package com.tpverp.backend.document;

import com.tpverp.backend.organization.CurrentOrganization;
import com.tpverp.backend.security.domain.UserAccount;
import com.tpverp.backend.terminal.*;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class SalePaymentSessionService {
 private final SalePaymentSessionRepository sessions; private final PosCashService sales; private final DocumentService documents; private final PosCardDocumentSnapshot snapshots;
 private final PaymentMethodRepository methods; private final CurrentOrganization organization; private final CurrentTerminal currentTerminal; private final CardTerminalConfigurationReader configurations; private final PaymentTerminalOperationService operations;
 public SalePaymentSessionService(SalePaymentSessionRepository sessions,PosCashService sales,DocumentService documents,PosCardDocumentSnapshot snapshots,PaymentMethodRepository methods,CurrentOrganization organization,CurrentTerminal currentTerminal,CardTerminalConfigurationReader configurations,PaymentTerminalOperationService operations){this.sessions=sessions;this.sales=sales;this.documents=documents;this.snapshots=snapshots;this.methods=methods;this.organization=organization;this.currentTerminal=currentTerminal;this.configurations=configurations;this.operations=operations;}

 @Transactional public SalePaymentSession reserve(UUID id,PosCashController.SaleRequest sale,Authentication auth){var command=sales.authoritativeCommand(sale);var quoted=documents.quoteTicket(command,auth);var requestHash=hash(sale,quoted.getTotal());var existing=sessions.findState(id);if(existing.isPresent()){var current=scoped(existing.orElseThrow(),auth);if(!current.getRequestHash().equals(requestHash))throw new IllegalStateException("payment_session_idempotency_conflict");return current;}var company=organization.currentCompany();var placeholder=methods.findByEmpresaIdAndNombreAndActivoTrue(company.getId(),"EFECTIVO").orElseGet(()->methods.findByEmpresaIdAndNombreAndActivoTrue(company.getId(),"TARJETA").orElseThrow());var user=requireUser(auth);var terminal=currentTerminal.terminalId(auth);var snapshot=ApprovedCardTicketSnapshot.from(quoted,placeholder.getId());return sessions.save(SalePaymentSession.reserve(id,quoted.getTiendaId(),terminal,user.getId(),requestHash,snapshots.serialize(snapshot),quoted.getTotal()));}
 @Transactional(readOnly=true) public SalePaymentSession get(UUID id,Authentication auth){return scoped(sessions.findState(id).orElseThrow(),auth);}
 @Transactional public SalePaymentSession add(UUID sessionId,UUID allocationId,String key,SalePaymentAllocationKind kind,BigDecimal amount,String provider,String reference,Authentication auth){var session=scoped(sessions.findLocked(sessionId).orElseThrow(),auth);var normalized=Money.euros(amount);var prior=session.getAllocations().stream().filter(a->a.getIdempotencyKey().equals(key)).findFirst();if(prior.isPresent()){var existing=prior.orElseThrow();if(existing.getKind()!=kind||existing.getAmount().compareTo(normalized)!=0||!Objects.equals(existing.getProvider(),provider))throw new IllegalStateException("allocation_idempotency_conflict");return session;}var a=session.addAllocation(allocationId,key,kind,normalized,provider,kind==SalePaymentAllocationKind.MANUAL_CARD?"MANUAL":kind==SalePaymentAllocationKind.INTEGRATED_CARD?"INTEGRATED":null);if(kind==SalePaymentAllocationKind.CASH)a.approve(null,null,null);else if(kind==SalePaymentAllocationKind.MANUAL_CARD)a.approve(null,reference,null);else {var config=configurations.required(session.getTerminalId());if(provider!=null&&!config.provider().name().equals(provider))throw new IllegalArgumentException("provider_not_configured");var result=operations.charge(allocationId,session.getRequestHash()+"|"+key,normalized,config);a.result(result.status(),allocationId,result.reference(),result.authorization(),result.message());}return sessions.save(session);}
 @Transactional public SalePaymentSession query(UUID sessionId,UUID allocationId,Authentication auth){var session=scoped(sessions.findLocked(sessionId).orElseThrow(),auth);var a=session.getAllocations().stream().filter(x->x.getId().equals(allocationId)&&x.getKind()==SalePaymentAllocationKind.INTEGRATED_CARD).findFirst().orElseThrow();var op=operations.recover(a.getOperationId()==null?a.getId():a.getOperationId(),UUID.randomUUID());a.result(op.getStatus(),a.getId(),op.getExternalReference(),op.getAuthorizationCode(),null);return sessions.save(session);}
 @Transactional public SalePaymentSession finalizeSession(UUID id,Authentication auth){var session=scoped(sessions.findLocked(id).orElseThrow(),auth);if(session.getTicketId()!=null)return session;if(!session.isCovered())throw new IllegalStateException("payment_session_not_covered");var company=organization.currentCompany();var cash=methods.findByEmpresaIdAndNombreAndActivoTrue(company.getId(),"EFECTIVO").orElseThrow();var card=methods.findByEmpresaIdAndNombreAndActivoTrue(company.getId(),"TARJETA").orElseThrow();var approved=session.getAllocations().stream().filter(a->a.getStatus()==PaymentTerminalOperationStatus.APPROVED).toList();var commands=new ArrayList<PaymentCommand>();for(int i=0;i<approved.size();i++){var a=approved.get(i);commands.add(new PaymentCommand(a.getKind()==SalePaymentAllocationKind.CASH?cash.getId():card.getId(),a.getAmount(),i==0,a.getKind()==SalePaymentAllocationKind.CASH?a.getAmount():null,a.getKind()==SalePaymentAllocationKind.CASH?Money.euros(BigDecimal.ZERO):null,null,a.getReference(),a.getKind()==SalePaymentAllocationKind.MANUAL_CARD?PaymentCardMode.MANUAL:a.getKind()==SalePaymentAllocationKind.INTEGRATED_CARD?PaymentCardMode.INTEGRATED:null,a.getKind()==SalePaymentAllocationKind.INTEGRATED_CARD?PaymentTerminalProvider.valueOf(a.getProvider()):null,a.getKind()==SalePaymentAllocationKind.INTEGRATED_CARD?PaymentTerminalOperationStatus.APPROVED:null,a.getAuthorization(),a.getKind()==SalePaymentAllocationKind.INTEGRATED_CARD?session.getTerminalId():null));}var ticket=documents.createApprovedCardTicketFromSnapshot(snapshots.deserialize(session.getSnapshot()),commands,auth);session.finalizeWith(ticket.getId(),ticket.getNumero());for(int i=0;i<approved.size();i++){var a=approved.get(i);if(a.getOperationId()!=null)operations.linkDocument(a.getOperationId(),ticket.getId(),ticket.getPagos().get(i).getId());}return sessions.save(session);}
 @Transactional public SalePaymentSession cancel(UUID id,Authentication auth){var s=scoped(sessions.findLocked(id).orElseThrow(),auth);s.cancel();return sessions.save(s);}
 private SalePaymentSession scoped(SalePaymentSession s,Authentication auth){if(!s.getStoreId().equals(organization.currentStore().getId())||!s.getTerminalId().equals(currentTerminal.terminalId(auth)))throw new NoSuchElementException();return s;}
 private static UserAccount requireUser(Authentication a){if(a.getPrincipal() instanceof UserAccount u)return u;throw new IllegalStateException("user_required");}
 private static String hash(PosCashController.SaleRequest sale,BigDecimal total){try{var md=MessageDigest.getInstance("SHA-256");return java.util.HexFormat.of().formatHex(md.digest((sale.toString()+Money.euros(total)).getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
